#include "hyper/lib/Parse/Lexer.cpp"
#include <iostream>
using namespace hyper::parse;
static int failures=0; static void check(bool v,const char*n){if(!v){std::cerr<<"FAIL "<<n<<"\n";++failures;}}
int main(){
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_0"); check(t.text=="café","unicode_text_0"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_1"); check(t.text=="世界","unicode_text_1"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_2"); check(t.text=="Привет","unicode_text_2"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_3"); check(t.text=="مرحبا","unicode_text_3"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_4"); check(t.text=="こんにちは","unicode_text_4"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_5"); check(t.text=="한국어","unicode_text_5"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_6"); check(t.text=="γειά","unicode_text_6"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_7"); check(t.text=="שלום","unicode_text_7"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_8"); check(t.text=="नमस्ते","unicode_text_8"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_9"); check(t.text=="გამარჯობა","unicode_text_9"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_10"); check(t.text=="café","unicode_text_10"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_11"); check(t.text=="世界","unicode_text_11"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_12"); check(t.text=="Привет","unicode_text_12"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_13"); check(t.text=="مرحبا","unicode_text_13"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_14"); check(t.text=="こんにちは","unicode_text_14"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_15"); check(t.text=="한국어","unicode_text_15"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_16"); check(t.text=="γειά","unicode_text_16"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_17"); check(t.text=="שלום","unicode_text_17"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_18"); check(t.text=="नमस्ते","unicode_text_18"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_19"); check(t.text=="გამარჯობა","unicode_text_19"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_20"); check(t.text=="café","unicode_text_20"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_21"); check(t.text=="世界","unicode_text_21"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_22"); check(t.text=="Привет","unicode_text_22"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_23"); check(t.text=="مرحبا","unicode_text_23"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_24"); check(t.text=="こんにちは","unicode_text_24"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_25"); check(t.text=="한국어","unicode_text_25"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_26"); check(t.text=="γειά","unicode_text_26"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_27"); check(t.text=="שלום","unicode_text_27"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_28"); check(t.text=="नमस्ते","unicode_text_28"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_29"); check(t.text=="გამარჯობა","unicode_text_29"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_30"); check(t.text=="café","unicode_text_30"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_31"); check(t.text=="世界","unicode_text_31"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_32"); check(t.text=="Привет","unicode_text_32"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_33"); check(t.text=="مرحبا","unicode_text_33"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_34"); check(t.text=="こんにちは","unicode_text_34"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_35"); check(t.text=="한국어","unicode_text_35"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_36"); check(t.text=="γειά","unicode_text_36"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_37"); check(t.text=="שלום","unicode_text_37"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_38"); check(t.text=="नमस्ते","unicode_text_38"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_39"); check(t.text=="გამარჯობა","unicode_text_39"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_40"); check(t.text=="café","unicode_text_40"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_41"); check(t.text=="世界","unicode_text_41"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_42"); check(t.text=="Привет","unicode_text_42"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_43"); check(t.text=="مرحبا","unicode_text_43"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_44"); check(t.text=="こんにちは","unicode_text_44"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_45"); check(t.text=="한국어","unicode_text_45"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_46"); check(t.text=="γειά","unicode_text_46"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_47"); check(t.text=="שלום","unicode_text_47"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_48"); check(t.text=="नमस्ते","unicode_text_48"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_49"); check(t.text=="გამარჯობა","unicode_text_49"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_50"); check(t.text=="café","unicode_text_50"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_51"); check(t.text=="世界","unicode_text_51"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_52"); check(t.text=="Привет","unicode_text_52"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_53"); check(t.text=="مرحبا","unicode_text_53"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_54"); check(t.text=="こんにちは","unicode_text_54"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_55"); check(t.text=="한국어","unicode_text_55"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_56"); check(t.text=="γειά","unicode_text_56"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_57"); check(t.text=="שלום","unicode_text_57"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_58"); check(t.text=="नमस्ते","unicode_text_58"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_59"); check(t.text=="გამარჯობა","unicode_text_59"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_60"); check(t.text=="café","unicode_text_60"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_61"); check(t.text=="世界","unicode_text_61"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_62"); check(t.text=="Привет","unicode_text_62"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_63"); check(t.text=="مرحبا","unicode_text_63"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_64"); check(t.text=="こんにちは","unicode_text_64"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_65"); check(t.text=="한국어","unicode_text_65"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_66"); check(t.text=="γειά","unicode_text_66"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_67"); check(t.text=="שלום","unicode_text_67"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_68"); check(t.text=="नमस्ते","unicode_text_68"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_69"); check(t.text=="გამარჯობა","unicode_text_69"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_70"); check(t.text=="café","unicode_text_70"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_71"); check(t.text=="世界","unicode_text_71"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_72"); check(t.text=="Привет","unicode_text_72"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_73"); check(t.text=="مرحبا","unicode_text_73"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_74"); check(t.text=="こんにちは","unicode_text_74"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_75"); check(t.text=="한국어","unicode_text_75"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_76"); check(t.text=="γειά","unicode_text_76"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_77"); check(t.text=="שלום","unicode_text_77"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_78"); check(t.text=="नमस्ते","unicode_text_78"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_79"); check(t.text=="გამარჯობა","unicode_text_79"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_80"); check(t.text=="café","unicode_text_80"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_81"); check(t.text=="世界","unicode_text_81"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_82"); check(t.text=="Привет","unicode_text_82"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_83"); check(t.text=="مرحبا","unicode_text_83"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_84"); check(t.text=="こんにちは","unicode_text_84"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_85"); check(t.text=="한국어","unicode_text_85"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_86"); check(t.text=="γειά","unicode_text_86"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_87"); check(t.text=="שלום","unicode_text_87"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_88"); check(t.text=="नमस्ते","unicode_text_88"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_89"); check(t.text=="გამარჯობა","unicode_text_89"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_90"); check(t.text=="café","unicode_text_90"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_91"); check(t.text=="世界","unicode_text_91"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_92"); check(t.text=="Привет","unicode_text_92"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_93"); check(t.text=="مرحبا","unicode_text_93"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_94"); check(t.text=="こんにちは","unicode_text_94"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_95"); check(t.text=="한국어","unicode_text_95"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_96"); check(t.text=="γειά","unicode_text_96"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_97"); check(t.text=="שלום","unicode_text_97"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_98"); check(t.text=="नमस्ते","unicode_text_98"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_99"); check(t.text=="გამარჯობა","unicode_text_99"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_100"); check(t.text=="café","unicode_text_100"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_101"); check(t.text=="世界","unicode_text_101"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_102"); check(t.text=="Привет","unicode_text_102"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_103"); check(t.text=="مرحبا","unicode_text_103"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_104"); check(t.text=="こんにちは","unicode_text_104"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_105"); check(t.text=="한국어","unicode_text_105"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_106"); check(t.text=="γειά","unicode_text_106"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_107"); check(t.text=="שלום","unicode_text_107"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_108"); check(t.text=="नमस्ते","unicode_text_108"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_109"); check(t.text=="გამარჯობა","unicode_text_109"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_110"); check(t.text=="café","unicode_text_110"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_111"); check(t.text=="世界","unicode_text_111"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_112"); check(t.text=="Привет","unicode_text_112"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_113"); check(t.text=="مرحبا","unicode_text_113"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_114"); check(t.text=="こんにちは","unicode_text_114"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_115"); check(t.text=="한국어","unicode_text_115"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_116"); check(t.text=="γειά","unicode_text_116"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_117"); check(t.text=="שלום","unicode_text_117"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_118"); check(t.text=="नमस्ते","unicode_text_118"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_119"); check(t.text=="გამარჯობა","unicode_text_119"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_120"); check(t.text=="café","unicode_text_120"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_121"); check(t.text=="世界","unicode_text_121"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_122"); check(t.text=="Привет","unicode_text_122"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_123"); check(t.text=="مرحبا","unicode_text_123"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_124"); check(t.text=="こんにちは","unicode_text_124"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_125"); check(t.text=="한국어","unicode_text_125"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_126"); check(t.text=="γειά","unicode_text_126"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_127"); check(t.text=="שלום","unicode_text_127"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_128"); check(t.text=="नमस्ते","unicode_text_128"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_129"); check(t.text=="გამარჯობა","unicode_text_129"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_130"); check(t.text=="café","unicode_text_130"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_131"); check(t.text=="世界","unicode_text_131"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_132"); check(t.text=="Привет","unicode_text_132"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_133"); check(t.text=="مرحبا","unicode_text_133"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_134"); check(t.text=="こんにちは","unicode_text_134"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_135"); check(t.text=="한국어","unicode_text_135"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_136"); check(t.text=="γειά","unicode_text_136"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_137"); check(t.text=="שלום","unicode_text_137"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_138"); check(t.text=="नमस्ते","unicode_text_138"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_139"); check(t.text=="გამარჯობა","unicode_text_139"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_140"); check(t.text=="café","unicode_text_140"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_141"); check(t.text=="世界","unicode_text_141"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_142"); check(t.text=="Привет","unicode_text_142"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_143"); check(t.text=="مرحبا","unicode_text_143"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_144"); check(t.text=="こんにちは","unicode_text_144"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_145"); check(t.text=="한국어","unicode_text_145"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_146"); check(t.text=="γειά","unicode_text_146"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_147"); check(t.text=="שלום","unicode_text_147"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_148"); check(t.text=="नमस्ते","unicode_text_148"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_149"); check(t.text=="გამარჯობა","unicode_text_149"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_150"); check(t.text=="café","unicode_text_150"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_151"); check(t.text=="世界","unicode_text_151"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_152"); check(t.text=="Привет","unicode_text_152"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_153"); check(t.text=="مرحبا","unicode_text_153"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_154"); check(t.text=="こんにちは","unicode_text_154"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_155"); check(t.text=="한국어","unicode_text_155"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_156"); check(t.text=="γειά","unicode_text_156"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_157"); check(t.text=="שלום","unicode_text_157"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_158"); check(t.text=="नमस्ते","unicode_text_158"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_159"); check(t.text=="გამარჯობა","unicode_text_159"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_160"); check(t.text=="café","unicode_text_160"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_161"); check(t.text=="世界","unicode_text_161"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_162"); check(t.text=="Привет","unicode_text_162"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_163"); check(t.text=="مرحبا","unicode_text_163"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_164"); check(t.text=="こんにちは","unicode_text_164"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_165"); check(t.text=="한국어","unicode_text_165"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_166"); check(t.text=="γειά","unicode_text_166"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_167"); check(t.text=="שלום","unicode_text_167"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_168"); check(t.text=="नमस्ते","unicode_text_168"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_169"); check(t.text=="გამარჯობა","unicode_text_169"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_170"); check(t.text=="café","unicode_text_170"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_171"); check(t.text=="世界","unicode_text_171"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_172"); check(t.text=="Привет","unicode_text_172"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_173"); check(t.text=="مرحبا","unicode_text_173"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_174"); check(t.text=="こんにちは","unicode_text_174"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_175"); check(t.text=="한국어","unicode_text_175"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_176"); check(t.text=="γειά","unicode_text_176"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_177"); check(t.text=="שלום","unicode_text_177"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_178"); check(t.text=="नमस्ते","unicode_text_178"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_179"); check(t.text=="გამარჯობა","unicode_text_179"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_180"); check(t.text=="café","unicode_text_180"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_181"); check(t.text=="世界","unicode_text_181"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_182"); check(t.text=="Привет","unicode_text_182"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_183"); check(t.text=="مرحبا","unicode_text_183"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_184"); check(t.text=="こんにちは","unicode_text_184"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_185"); check(t.text=="한국어","unicode_text_185"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_186"); check(t.text=="γειά","unicode_text_186"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_187"); check(t.text=="שלום","unicode_text_187"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_188"); check(t.text=="नमस्ते","unicode_text_188"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_189"); check(t.text=="გამარჯობა","unicode_text_189"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_190"); check(t.text=="café","unicode_text_190"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_191"); check(t.text=="世界","unicode_text_191"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_192"); check(t.text=="Привет","unicode_text_192"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_193"); check(t.text=="مرحبا","unicode_text_193"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_194"); check(t.text=="こんにちは","unicode_text_194"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_195"); check(t.text=="한국어","unicode_text_195"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_196"); check(t.text=="γειά","unicode_text_196"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_197"); check(t.text=="שלום","unicode_text_197"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_198"); check(t.text=="नमस्ते","unicode_text_198"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_199"); check(t.text=="გამარჯობა","unicode_text_199"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_200"); check(t.text=="café","unicode_text_200"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_201"); check(t.text=="世界","unicode_text_201"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_202"); check(t.text=="Привет","unicode_text_202"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_203"); check(t.text=="مرحبا","unicode_text_203"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_204"); check(t.text=="こんにちは","unicode_text_204"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_205"); check(t.text=="한국어","unicode_text_205"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_206"); check(t.text=="γειά","unicode_text_206"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_207"); check(t.text=="שלום","unicode_text_207"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_208"); check(t.text=="नमस्ते","unicode_text_208"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_209"); check(t.text=="გამარჯობა","unicode_text_209"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_210"); check(t.text=="café","unicode_text_210"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_211"); check(t.text=="世界","unicode_text_211"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_212"); check(t.text=="Привет","unicode_text_212"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_213"); check(t.text=="مرحبا","unicode_text_213"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_214"); check(t.text=="こんにちは","unicode_text_214"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_215"); check(t.text=="한국어","unicode_text_215"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_216"); check(t.text=="γειά","unicode_text_216"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_217"); check(t.text=="שלום","unicode_text_217"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_218"); check(t.text=="नमस्ते","unicode_text_218"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_219"); check(t.text=="გამარჯობა","unicode_text_219"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_220"); check(t.text=="café","unicode_text_220"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_221"); check(t.text=="世界","unicode_text_221"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_222"); check(t.text=="Привет","unicode_text_222"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_223"); check(t.text=="مرحبا","unicode_text_223"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_224"); check(t.text=="こんにちは","unicode_text_224"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_225"); check(t.text=="한국어","unicode_text_225"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_226"); check(t.text=="γειά","unicode_text_226"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_227"); check(t.text=="שלום","unicode_text_227"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_228"); check(t.text=="नमस्ते","unicode_text_228"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_229"); check(t.text=="გამარჯობა","unicode_text_229"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_230"); check(t.text=="café","unicode_text_230"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_231"); check(t.text=="世界","unicode_text_231"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_232"); check(t.text=="Привет","unicode_text_232"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_233"); check(t.text=="مرحبا","unicode_text_233"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_234"); check(t.text=="こんにちは","unicode_text_234"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_235"); check(t.text=="한국어","unicode_text_235"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_236"); check(t.text=="γειά","unicode_text_236"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_237"); check(t.text=="שלום","unicode_text_237"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_238"); check(t.text=="नमस्ते","unicode_text_238"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_239"); check(t.text=="გამარჯობა","unicode_text_239"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_240"); check(t.text=="café","unicode_text_240"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_241"); check(t.text=="世界","unicode_text_241"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_242"); check(t.text=="Привет","unicode_text_242"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_243"); check(t.text=="مرحبا","unicode_text_243"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_244"); check(t.text=="こんにちは","unicode_text_244"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_245"); check(t.text=="한국어","unicode_text_245"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_246"); check(t.text=="γειά","unicode_text_246"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_247"); check(t.text=="שלום","unicode_text_247"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_248"); check(t.text=="नमस्ते","unicode_text_248"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_249"); check(t.text=="გამარჯობა","unicode_text_249"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_250"); check(t.text=="café","unicode_text_250"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_251"); check(t.text=="世界","unicode_text_251"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_252"); check(t.text=="Привет","unicode_text_252"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_253"); check(t.text=="مرحبا","unicode_text_253"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_254"); check(t.text=="こんにちは","unicode_text_254"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_255"); check(t.text=="한국어","unicode_text_255"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_256"); check(t.text=="γειά","unicode_text_256"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_257"); check(t.text=="שלום","unicode_text_257"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_258"); check(t.text=="नमस्ते","unicode_text_258"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_259"); check(t.text=="გამარჯობა","unicode_text_259"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_260"); check(t.text=="café","unicode_text_260"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_261"); check(t.text=="世界","unicode_text_261"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_262"); check(t.text=="Привет","unicode_text_262"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_263"); check(t.text=="مرحبا","unicode_text_263"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_264"); check(t.text=="こんにちは","unicode_text_264"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_265"); check(t.text=="한국어","unicode_text_265"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_266"); check(t.text=="γειά","unicode_text_266"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_267"); check(t.text=="שלום","unicode_text_267"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_268"); check(t.text=="नमस्ते","unicode_text_268"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_269"); check(t.text=="გამარჯობა","unicode_text_269"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_270"); check(t.text=="café","unicode_text_270"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_271"); check(t.text=="世界","unicode_text_271"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_272"); check(t.text=="Привет","unicode_text_272"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_273"); check(t.text=="مرحبا","unicode_text_273"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_274"); check(t.text=="こんにちは","unicode_text_274"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_275"); check(t.text=="한국어","unicode_text_275"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_276"); check(t.text=="γειά","unicode_text_276"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_277"); check(t.text=="שלום","unicode_text_277"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_278"); check(t.text=="नमस्ते","unicode_text_278"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_279"); check(t.text=="გამარჯობა","unicode_text_279"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_280"); check(t.text=="café","unicode_text_280"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_281"); check(t.text=="世界","unicode_text_281"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_282"); check(t.text=="Привет","unicode_text_282"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_283"); check(t.text=="مرحبا","unicode_text_283"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_284"); check(t.text=="こんにちは","unicode_text_284"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_285"); check(t.text=="한국어","unicode_text_285"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_286"); check(t.text=="γειά","unicode_text_286"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_287"); check(t.text=="שלום","unicode_text_287"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_288"); check(t.text=="नमस्ते","unicode_text_288"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_289"); check(t.text=="გამარჯობა","unicode_text_289"); }
 { Lexer l("café"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_290"); check(t.text=="café","unicode_text_290"); }
 { Lexer l("世界"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_291"); check(t.text=="世界","unicode_text_291"); }
 { Lexer l("Привет"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_292"); check(t.text=="Привет","unicode_text_292"); }
 { Lexer l("مرحبا"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_293"); check(t.text=="مرحبا","unicode_text_293"); }
 { Lexer l("こんにちは"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_294"); check(t.text=="こんにちは","unicode_text_294"); }
 { Lexer l("한국어"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_295"); check(t.text=="한국어","unicode_text_295"); }
 { Lexer l("γειά"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_296"); check(t.text=="γειά","unicode_text_296"); }
 { Lexer l("שלום"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_297"); check(t.text=="שלום","unicode_text_297"); }
 { Lexer l("नमस्ते"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_298"); check(t.text=="नमस्ते","unicode_text_298"); }
 { Lexer l("გამარჯობა"); auto t=l.lex(); check(t.kind==TokenKind::Identifier,"unicode_299"); check(t.text=="გამარჯობა","unicode_text_299"); }
 return failures?1:0; }
