#include "hyper/lib/Parse/Lexer.h"
#include <iostream>
using namespace hyper::parse;
static int failures=0; static void check(bool v,const char*n){if(!v){std::cerr<<"FAIL "<<n<<"\n";++failures;}}
int main(){
 { Lexer l("function"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_0"); check(t.text=="function","kw_text_0"); }
 { Lexer l("var"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_1"); check(t.text=="var","kw_text_1"); }
 { Lexer l("const"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_2"); check(t.text=="const","kw_text_2"); }
 { Lexer l("struct"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_3"); check(t.text=="struct","kw_text_3"); }
 { Lexer l("class"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_4"); check(t.text=="class","kw_text_4"); }
 { Lexer l("enum"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_5"); check(t.text=="enum","kw_text_5"); }
 { Lexer l("protocol"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_6"); check(t.text=="protocol","kw_text_6"); }
 { Lexer l("extension"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_7"); check(t.text=="extension","kw_text_7"); }
 { Lexer l("type"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_8"); check(t.text=="type","kw_text_8"); }
 { Lexer l("typealias"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_9"); check(t.text=="typealias","kw_text_9"); }
 { Lexer l("template"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_10"); check(t.text=="template","kw_text_10"); }
 { Lexer l("typename"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_11"); check(t.text=="typename","kw_text_11"); }
 { Lexer l("operator"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_12"); check(t.text=="operator","kw_text_12"); }
 { Lexer l("namespace"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_13"); check(t.text=="namespace","kw_text_13"); }
 { Lexer l("module"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_14"); check(t.text=="module","kw_text_14"); }
 { Lexer l("init"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_15"); check(t.text=="init","kw_text_15"); }
 { Lexer l("deinit"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_16"); check(t.text=="deinit","kw_text_16"); }
 { Lexer l("self"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_17"); check(t.text=="self","kw_text_17"); }
 { Lexer l("super"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_18"); check(t.text=="super","kw_text_18"); }
 { Lexer l("new"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_19"); check(t.text=="new","kw_text_19"); }
 { Lexer l("get"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_20"); check(t.text=="get","kw_text_20"); }
 { Lexer l("set"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_21"); check(t.text=="set","kw_text_21"); }
 { Lexer l("if"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_22"); check(t.text=="if","kw_text_22"); }
 { Lexer l("elseif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_23"); check(t.text=="elseif","kw_text_23"); }
 { Lexer l("else"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_24"); check(t.text=="else","kw_text_24"); }
 { Lexer l("endif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_25"); check(t.text=="endif","kw_text_25"); }
 { Lexer l("switch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_26"); check(t.text=="switch","kw_text_26"); }
 { Lexer l("case"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_27"); check(t.text=="case","kw_text_27"); }
 { Lexer l("default"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_28"); check(t.text=="default","kw_text_28"); }
 { Lexer l("while"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_29"); check(t.text=="while","kw_text_29"); }
 { Lexer l("loop"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_30"); check(t.text=="loop","kw_text_30"); }
 { Lexer l("do"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_31"); check(t.text=="do","kw_text_31"); }
 { Lexer l("for"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_32"); check(t.text=="for","kw_text_32"); }
 { Lexer l("in"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_33"); check(t.text=="in","kw_text_33"); }
 { Lexer l("break"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_34"); check(t.text=="break","kw_text_34"); }
 { Lexer l("continue"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_35"); check(t.text=="continue","kw_text_35"); }
 { Lexer l("return"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_36"); check(t.text=="return","kw_text_36"); }
 { Lexer l("throw"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_37"); check(t.text=="throw","kw_text_37"); }
 { Lexer l("try"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_38"); check(t.text=="try","kw_text_38"); }
 { Lexer l("catch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_39"); check(t.text=="catch","kw_text_39"); }
 { Lexer l("finally"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_40"); check(t.text=="finally","kw_text_40"); }
 { Lexer l("defer"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_41"); check(t.text=="defer","kw_text_41"); }
 { Lexer l("error"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_42"); check(t.text=="error","kw_text_42"); }
 { Lexer l("panic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_43"); check(t.text=="panic","kw_text_43"); }
 { Lexer l("bool"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_44"); check(t.text=="bool","kw_text_44"); }
 { Lexer l("int"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_45"); check(t.text=="int","kw_text_45"); }
 { Lexer l("uint"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_46"); check(t.text=="uint","kw_text_46"); }
 { Lexer l("int8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_47"); check(t.text=="int8","kw_text_47"); }
 { Lexer l("int16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_48"); check(t.text=="int16","kw_text_48"); }
 { Lexer l("int32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_49"); check(t.text=="int32","kw_text_49"); }
 { Lexer l("int64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_50"); check(t.text=="int64","kw_text_50"); }
 { Lexer l("uint8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_51"); check(t.text=="uint8","kw_text_51"); }
 { Lexer l("uint16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_52"); check(t.text=="uint16","kw_text_52"); }
 { Lexer l("uint32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_53"); check(t.text=="uint32","kw_text_53"); }
 { Lexer l("uint64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_54"); check(t.text=="uint64","kw_text_54"); }
 { Lexer l("float"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_55"); check(t.text=="float","kw_text_55"); }
 { Lexer l("double"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_56"); check(t.text=="double","kw_text_56"); }
 { Lexer l("byte"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_57"); check(t.text=="byte","kw_text_57"); }
 { Lexer l("char"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_58"); check(t.text=="char","kw_text_58"); }
 { Lexer l("string"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_59"); check(t.text=="string","kw_text_59"); }
 { Lexer l("void"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_60"); check(t.text=="void","kw_text_60"); }
 { Lexer l("nil"); auto t=l.lex(); check(t.kind==TokenKind::NilLiteral,"kw_61"); check(t.text=="nil","kw_text_61"); }
 { Lexer l("public"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_62"); check(t.text=="public","kw_text_62"); }
 { Lexer l("private"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_63"); check(t.text=="private","kw_text_63"); }
 { Lexer l("protected"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_64"); check(t.text=="protected","kw_text_64"); }
 { Lexer l("internal"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_65"); check(t.text=="internal","kw_text_65"); }
 { Lexer l("static"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_66"); check(t.text=="static","kw_text_66"); }
 { Lexer l("extern"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_67"); check(t.text=="extern","kw_text_67"); }
 { Lexer l("inline"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_68"); check(t.text=="inline","kw_text_68"); }
 { Lexer l("volatile"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_69"); check(t.text=="volatile","kw_text_69"); }
 { Lexer l("sizeof"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_70"); check(t.text=="sizeof","kw_text_70"); }
 { Lexer l("async"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_71"); check(t.text=="async","kw_text_71"); }
 { Lexer l("await"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_72"); check(t.text=="await","kw_text_72"); }
 { Lexer l("task"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_73"); check(t.text=="task","kw_text_73"); }
 { Lexer l("actor"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_74"); check(t.text=="actor","kw_text_74"); }
 { Lexer l("parallel"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_75"); check(t.text=="parallel","kw_text_75"); }
 { Lexer l("atomic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_76"); check(t.text=="atomic","kw_text_76"); }
 { Lexer l("input"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_77"); check(t.text=="input","kw_text_77"); }
 { Lexer l("output"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_78"); check(t.text=="output","kw_text_78"); }
 { Lexer l("message"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_79"); check(t.text=="message","kw_text_79"); }
 { Lexer l("show"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_80"); check(t.text=="show","kw_text_80"); }
 { Lexer l("getData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_81"); check(t.text=="getData","kw_text_81"); }
 { Lexer l("createData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_82"); check(t.text=="createData","kw_text_82"); }
 { Lexer l("from"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_83"); check(t.text=="from","kw_text_83"); }
 { Lexer l("import"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_84"); check(t.text=="import","kw_text_84"); }
 { Lexer l("function"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_85"); check(t.text=="function","kw_text_85"); }
 { Lexer l("var"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_86"); check(t.text=="var","kw_text_86"); }
 { Lexer l("const"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_87"); check(t.text=="const","kw_text_87"); }
 { Lexer l("struct"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_88"); check(t.text=="struct","kw_text_88"); }
 { Lexer l("class"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_89"); check(t.text=="class","kw_text_89"); }
 { Lexer l("enum"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_90"); check(t.text=="enum","kw_text_90"); }
 { Lexer l("protocol"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_91"); check(t.text=="protocol","kw_text_91"); }
 { Lexer l("extension"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_92"); check(t.text=="extension","kw_text_92"); }
 { Lexer l("type"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_93"); check(t.text=="type","kw_text_93"); }
 { Lexer l("typealias"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_94"); check(t.text=="typealias","kw_text_94"); }
 { Lexer l("template"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_95"); check(t.text=="template","kw_text_95"); }
 { Lexer l("typename"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_96"); check(t.text=="typename","kw_text_96"); }
 { Lexer l("operator"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_97"); check(t.text=="operator","kw_text_97"); }
 { Lexer l("namespace"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_98"); check(t.text=="namespace","kw_text_98"); }
 { Lexer l("module"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_99"); check(t.text=="module","kw_text_99"); }
 { Lexer l("init"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_100"); check(t.text=="init","kw_text_100"); }
 { Lexer l("deinit"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_101"); check(t.text=="deinit","kw_text_101"); }
 { Lexer l("self"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_102"); check(t.text=="self","kw_text_102"); }
 { Lexer l("super"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_103"); check(t.text=="super","kw_text_103"); }
 { Lexer l("new"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_104"); check(t.text=="new","kw_text_104"); }
 { Lexer l("get"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_105"); check(t.text=="get","kw_text_105"); }
 { Lexer l("set"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_106"); check(t.text=="set","kw_text_106"); }
 { Lexer l("if"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_107"); check(t.text=="if","kw_text_107"); }
 { Lexer l("elseif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_108"); check(t.text=="elseif","kw_text_108"); }
 { Lexer l("else"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_109"); check(t.text=="else","kw_text_109"); }
 { Lexer l("endif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_110"); check(t.text=="endif","kw_text_110"); }
 { Lexer l("switch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_111"); check(t.text=="switch","kw_text_111"); }
 { Lexer l("case"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_112"); check(t.text=="case","kw_text_112"); }
 { Lexer l("default"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_113"); check(t.text=="default","kw_text_113"); }
 { Lexer l("while"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_114"); check(t.text=="while","kw_text_114"); }
 { Lexer l("loop"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_115"); check(t.text=="loop","kw_text_115"); }
 { Lexer l("do"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_116"); check(t.text=="do","kw_text_116"); }
 { Lexer l("for"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_117"); check(t.text=="for","kw_text_117"); }
 { Lexer l("in"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_118"); check(t.text=="in","kw_text_118"); }
 { Lexer l("break"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_119"); check(t.text=="break","kw_text_119"); }
 { Lexer l("continue"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_120"); check(t.text=="continue","kw_text_120"); }
 { Lexer l("return"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_121"); check(t.text=="return","kw_text_121"); }
 { Lexer l("throw"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_122"); check(t.text=="throw","kw_text_122"); }
 { Lexer l("try"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_123"); check(t.text=="try","kw_text_123"); }
 { Lexer l("catch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_124"); check(t.text=="catch","kw_text_124"); }
 { Lexer l("finally"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_125"); check(t.text=="finally","kw_text_125"); }
 { Lexer l("defer"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_126"); check(t.text=="defer","kw_text_126"); }
 { Lexer l("error"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_127"); check(t.text=="error","kw_text_127"); }
 { Lexer l("panic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_128"); check(t.text=="panic","kw_text_128"); }
 { Lexer l("bool"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_129"); check(t.text=="bool","kw_text_129"); }
 { Lexer l("int"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_130"); check(t.text=="int","kw_text_130"); }
 { Lexer l("uint"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_131"); check(t.text=="uint","kw_text_131"); }
 { Lexer l("int8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_132"); check(t.text=="int8","kw_text_132"); }
 { Lexer l("int16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_133"); check(t.text=="int16","kw_text_133"); }
 { Lexer l("int32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_134"); check(t.text=="int32","kw_text_134"); }
 { Lexer l("int64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_135"); check(t.text=="int64","kw_text_135"); }
 { Lexer l("uint8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_136"); check(t.text=="uint8","kw_text_136"); }
 { Lexer l("uint16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_137"); check(t.text=="uint16","kw_text_137"); }
 { Lexer l("uint32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_138"); check(t.text=="uint32","kw_text_138"); }
 { Lexer l("uint64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_139"); check(t.text=="uint64","kw_text_139"); }
 { Lexer l("float"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_140"); check(t.text=="float","kw_text_140"); }
 { Lexer l("double"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_141"); check(t.text=="double","kw_text_141"); }
 { Lexer l("byte"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_142"); check(t.text=="byte","kw_text_142"); }
 { Lexer l("char"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_143"); check(t.text=="char","kw_text_143"); }
 { Lexer l("string"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_144"); check(t.text=="string","kw_text_144"); }
 { Lexer l("void"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_145"); check(t.text=="void","kw_text_145"); }
 { Lexer l("nil"); auto t=l.lex(); check(t.kind==TokenKind::NilLiteral,"kw_146"); check(t.text=="nil","kw_text_146"); }
 { Lexer l("public"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_147"); check(t.text=="public","kw_text_147"); }
 { Lexer l("private"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_148"); check(t.text=="private","kw_text_148"); }
 { Lexer l("protected"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_149"); check(t.text=="protected","kw_text_149"); }
 { Lexer l("internal"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_150"); check(t.text=="internal","kw_text_150"); }
 { Lexer l("static"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_151"); check(t.text=="static","kw_text_151"); }
 { Lexer l("extern"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_152"); check(t.text=="extern","kw_text_152"); }
 { Lexer l("inline"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_153"); check(t.text=="inline","kw_text_153"); }
 { Lexer l("volatile"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_154"); check(t.text=="volatile","kw_text_154"); }
 { Lexer l("sizeof"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_155"); check(t.text=="sizeof","kw_text_155"); }
 { Lexer l("async"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_156"); check(t.text=="async","kw_text_156"); }
 { Lexer l("await"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_157"); check(t.text=="await","kw_text_157"); }
 { Lexer l("task"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_158"); check(t.text=="task","kw_text_158"); }
 { Lexer l("actor"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_159"); check(t.text=="actor","kw_text_159"); }
 { Lexer l("parallel"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_160"); check(t.text=="parallel","kw_text_160"); }
 { Lexer l("atomic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_161"); check(t.text=="atomic","kw_text_161"); }
 { Lexer l("input"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_162"); check(t.text=="input","kw_text_162"); }
 { Lexer l("output"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_163"); check(t.text=="output","kw_text_163"); }
 { Lexer l("message"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_164"); check(t.text=="message","kw_text_164"); }
 { Lexer l("show"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_165"); check(t.text=="show","kw_text_165"); }
 { Lexer l("getData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_166"); check(t.text=="getData","kw_text_166"); }
 { Lexer l("createData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_167"); check(t.text=="createData","kw_text_167"); }
 { Lexer l("from"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_168"); check(t.text=="from","kw_text_168"); }
 { Lexer l("import"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_169"); check(t.text=="import","kw_text_169"); }
 { Lexer l("function"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_170"); check(t.text=="function","kw_text_170"); }
 { Lexer l("var"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_171"); check(t.text=="var","kw_text_171"); }
 { Lexer l("const"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_172"); check(t.text=="const","kw_text_172"); }
 { Lexer l("struct"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_173"); check(t.text=="struct","kw_text_173"); }
 { Lexer l("class"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_174"); check(t.text=="class","kw_text_174"); }
 { Lexer l("enum"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_175"); check(t.text=="enum","kw_text_175"); }
 { Lexer l("protocol"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_176"); check(t.text=="protocol","kw_text_176"); }
 { Lexer l("extension"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_177"); check(t.text=="extension","kw_text_177"); }
 { Lexer l("type"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_178"); check(t.text=="type","kw_text_178"); }
 { Lexer l("typealias"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_179"); check(t.text=="typealias","kw_text_179"); }
 { Lexer l("template"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_180"); check(t.text=="template","kw_text_180"); }
 { Lexer l("typename"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_181"); check(t.text=="typename","kw_text_181"); }
 { Lexer l("operator"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_182"); check(t.text=="operator","kw_text_182"); }
 { Lexer l("namespace"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_183"); check(t.text=="namespace","kw_text_183"); }
 { Lexer l("module"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_184"); check(t.text=="module","kw_text_184"); }
 { Lexer l("init"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_185"); check(t.text=="init","kw_text_185"); }
 { Lexer l("deinit"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_186"); check(t.text=="deinit","kw_text_186"); }
 { Lexer l("self"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_187"); check(t.text=="self","kw_text_187"); }
 { Lexer l("super"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_188"); check(t.text=="super","kw_text_188"); }
 { Lexer l("new"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_189"); check(t.text=="new","kw_text_189"); }
 { Lexer l("get"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_190"); check(t.text=="get","kw_text_190"); }
 { Lexer l("set"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_191"); check(t.text=="set","kw_text_191"); }
 { Lexer l("if"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_192"); check(t.text=="if","kw_text_192"); }
 { Lexer l("elseif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_193"); check(t.text=="elseif","kw_text_193"); }
 { Lexer l("else"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_194"); check(t.text=="else","kw_text_194"); }
 { Lexer l("endif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_195"); check(t.text=="endif","kw_text_195"); }
 { Lexer l("switch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_196"); check(t.text=="switch","kw_text_196"); }
 { Lexer l("case"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_197"); check(t.text=="case","kw_text_197"); }
 { Lexer l("default"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_198"); check(t.text=="default","kw_text_198"); }
 { Lexer l("while"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_199"); check(t.text=="while","kw_text_199"); }
 { Lexer l("loop"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_200"); check(t.text=="loop","kw_text_200"); }
 { Lexer l("do"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_201"); check(t.text=="do","kw_text_201"); }
 { Lexer l("for"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_202"); check(t.text=="for","kw_text_202"); }
 { Lexer l("in"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_203"); check(t.text=="in","kw_text_203"); }
 { Lexer l("break"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_204"); check(t.text=="break","kw_text_204"); }
 { Lexer l("continue"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_205"); check(t.text=="continue","kw_text_205"); }
 { Lexer l("return"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_206"); check(t.text=="return","kw_text_206"); }
 { Lexer l("throw"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_207"); check(t.text=="throw","kw_text_207"); }
 { Lexer l("try"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_208"); check(t.text=="try","kw_text_208"); }
 { Lexer l("catch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_209"); check(t.text=="catch","kw_text_209"); }
 { Lexer l("finally"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_210"); check(t.text=="finally","kw_text_210"); }
 { Lexer l("defer"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_211"); check(t.text=="defer","kw_text_211"); }
 { Lexer l("error"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_212"); check(t.text=="error","kw_text_212"); }
 { Lexer l("panic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_213"); check(t.text=="panic","kw_text_213"); }
 { Lexer l("bool"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_214"); check(t.text=="bool","kw_text_214"); }
 { Lexer l("int"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_215"); check(t.text=="int","kw_text_215"); }
 { Lexer l("uint"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_216"); check(t.text=="uint","kw_text_216"); }
 { Lexer l("int8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_217"); check(t.text=="int8","kw_text_217"); }
 { Lexer l("int16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_218"); check(t.text=="int16","kw_text_218"); }
 { Lexer l("int32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_219"); check(t.text=="int32","kw_text_219"); }
 { Lexer l("int64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_220"); check(t.text=="int64","kw_text_220"); }
 { Lexer l("uint8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_221"); check(t.text=="uint8","kw_text_221"); }
 { Lexer l("uint16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_222"); check(t.text=="uint16","kw_text_222"); }
 { Lexer l("uint32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_223"); check(t.text=="uint32","kw_text_223"); }
 { Lexer l("uint64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_224"); check(t.text=="uint64","kw_text_224"); }
 { Lexer l("float"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_225"); check(t.text=="float","kw_text_225"); }
 { Lexer l("double"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_226"); check(t.text=="double","kw_text_226"); }
 { Lexer l("byte"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_227"); check(t.text=="byte","kw_text_227"); }
 { Lexer l("char"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_228"); check(t.text=="char","kw_text_228"); }
 { Lexer l("string"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_229"); check(t.text=="string","kw_text_229"); }
 { Lexer l("void"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_230"); check(t.text=="void","kw_text_230"); }
 { Lexer l("nil"); auto t=l.lex(); check(t.kind==TokenKind::NilLiteral,"kw_231"); check(t.text=="nil","kw_text_231"); }
 { Lexer l("public"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_232"); check(t.text=="public","kw_text_232"); }
 { Lexer l("private"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_233"); check(t.text=="private","kw_text_233"); }
 { Lexer l("protected"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_234"); check(t.text=="protected","kw_text_234"); }
 { Lexer l("internal"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_235"); check(t.text=="internal","kw_text_235"); }
 { Lexer l("static"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_236"); check(t.text=="static","kw_text_236"); }
 { Lexer l("extern"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_237"); check(t.text=="extern","kw_text_237"); }
 { Lexer l("inline"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_238"); check(t.text=="inline","kw_text_238"); }
 { Lexer l("volatile"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_239"); check(t.text=="volatile","kw_text_239"); }
 { Lexer l("sizeof"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_240"); check(t.text=="sizeof","kw_text_240"); }
 { Lexer l("async"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_241"); check(t.text=="async","kw_text_241"); }
 { Lexer l("await"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_242"); check(t.text=="await","kw_text_242"); }
 { Lexer l("task"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_243"); check(t.text=="task","kw_text_243"); }
 { Lexer l("actor"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_244"); check(t.text=="actor","kw_text_244"); }
 { Lexer l("parallel"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_245"); check(t.text=="parallel","kw_text_245"); }
 { Lexer l("atomic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_246"); check(t.text=="atomic","kw_text_246"); }
 { Lexer l("input"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_247"); check(t.text=="input","kw_text_247"); }
 { Lexer l("output"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_248"); check(t.text=="output","kw_text_248"); }
 { Lexer l("message"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_249"); check(t.text=="message","kw_text_249"); }
 { Lexer l("show"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_250"); check(t.text=="show","kw_text_250"); }
 { Lexer l("getData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_251"); check(t.text=="getData","kw_text_251"); }
 { Lexer l("createData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_252"); check(t.text=="createData","kw_text_252"); }
 { Lexer l("from"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_253"); check(t.text=="from","kw_text_253"); }
 { Lexer l("import"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_254"); check(t.text=="import","kw_text_254"); }
 { Lexer l("function"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_255"); check(t.text=="function","kw_text_255"); }
 { Lexer l("var"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_256"); check(t.text=="var","kw_text_256"); }
 { Lexer l("const"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_257"); check(t.text=="const","kw_text_257"); }
 { Lexer l("struct"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_258"); check(t.text=="struct","kw_text_258"); }
 { Lexer l("class"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_259"); check(t.text=="class","kw_text_259"); }
 { Lexer l("enum"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_260"); check(t.text=="enum","kw_text_260"); }
 { Lexer l("protocol"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_261"); check(t.text=="protocol","kw_text_261"); }
 { Lexer l("extension"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_262"); check(t.text=="extension","kw_text_262"); }
 { Lexer l("type"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_263"); check(t.text=="type","kw_text_263"); }
 { Lexer l("typealias"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_264"); check(t.text=="typealias","kw_text_264"); }
 { Lexer l("template"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_265"); check(t.text=="template","kw_text_265"); }
 { Lexer l("typename"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_266"); check(t.text=="typename","kw_text_266"); }
 { Lexer l("operator"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_267"); check(t.text=="operator","kw_text_267"); }
 { Lexer l("namespace"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_268"); check(t.text=="namespace","kw_text_268"); }
 { Lexer l("module"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_269"); check(t.text=="module","kw_text_269"); }
 { Lexer l("init"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_270"); check(t.text=="init","kw_text_270"); }
 { Lexer l("deinit"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_271"); check(t.text=="deinit","kw_text_271"); }
 { Lexer l("self"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_272"); check(t.text=="self","kw_text_272"); }
 { Lexer l("super"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_273"); check(t.text=="super","kw_text_273"); }
 { Lexer l("new"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_274"); check(t.text=="new","kw_text_274"); }
 { Lexer l("get"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_275"); check(t.text=="get","kw_text_275"); }
 { Lexer l("set"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_276"); check(t.text=="set","kw_text_276"); }
 { Lexer l("if"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_277"); check(t.text=="if","kw_text_277"); }
 { Lexer l("elseif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_278"); check(t.text=="elseif","kw_text_278"); }
 { Lexer l("else"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_279"); check(t.text=="else","kw_text_279"); }
 { Lexer l("endif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_280"); check(t.text=="endif","kw_text_280"); }
 { Lexer l("switch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_281"); check(t.text=="switch","kw_text_281"); }
 { Lexer l("case"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_282"); check(t.text=="case","kw_text_282"); }
 { Lexer l("default"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_283"); check(t.text=="default","kw_text_283"); }
 { Lexer l("while"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_284"); check(t.text=="while","kw_text_284"); }
 { Lexer l("loop"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_285"); check(t.text=="loop","kw_text_285"); }
 { Lexer l("do"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_286"); check(t.text=="do","kw_text_286"); }
 { Lexer l("for"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_287"); check(t.text=="for","kw_text_287"); }
 { Lexer l("in"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_288"); check(t.text=="in","kw_text_288"); }
 { Lexer l("break"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_289"); check(t.text=="break","kw_text_289"); }
 { Lexer l("continue"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_290"); check(t.text=="continue","kw_text_290"); }
 { Lexer l("return"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_291"); check(t.text=="return","kw_text_291"); }
 { Lexer l("throw"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_292"); check(t.text=="throw","kw_text_292"); }
 { Lexer l("try"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_293"); check(t.text=="try","kw_text_293"); }
 { Lexer l("catch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_294"); check(t.text=="catch","kw_text_294"); }
 { Lexer l("finally"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_295"); check(t.text=="finally","kw_text_295"); }
 { Lexer l("defer"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_296"); check(t.text=="defer","kw_text_296"); }
 { Lexer l("error"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_297"); check(t.text=="error","kw_text_297"); }
 { Lexer l("panic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_298"); check(t.text=="panic","kw_text_298"); }
 { Lexer l("bool"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"kw_299"); check(t.text=="bool","kw_text_299"); }
 return failures?1:0; }
