#include "hyper/lib/Parse/Lexer.h"
#include <iostream>
using namespace hyper::parse;
static int failures=0;
static void check(bool v,const char*n){if(!v){std::cerr<<"FAIL "<<n<<"\n";++failures;}}
int main(){
  { Lexer l("0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_0"); check(t.text=="0","literal_text_0"); check(l.lex().isEOF(),"literal_eof_0"); }
  { Lexer l(" 0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_0"); }
  { Lexer l("1"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_1"); check(t.text=="1","literal_text_1"); check(l.lex().isEOF(),"literal_eof_1"); }
  { Lexer l(" 1 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_1"); }
  { Lexer l("42"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_2"); check(t.text=="42","literal_text_2"); check(l.lex().isEOF(),"literal_eof_2"); }
  { Lexer l(" 42 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_2"); }
  { Lexer l("999999"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_3"); check(t.text=="999999","literal_text_3"); check(l.lex().isEOF(),"literal_eof_3"); }
  { Lexer l(" 999999 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_3"); }
  { Lexer l("0x0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_4"); check(t.text=="0x0","literal_text_4"); check(l.lex().isEOF(),"literal_eof_4"); }
  { Lexer l(" 0x0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_4"); }
  { Lexer l("0xff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_5"); check(t.text=="0xff","literal_text_5"); check(l.lex().isEOF(),"literal_eof_5"); }
  { Lexer l(" 0xff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_5"); }
  { Lexer l("0XAB"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_6"); check(t.text=="0XAB","literal_text_6"); check(l.lex().isEOF(),"literal_eof_6"); }
  { Lexer l(" 0XAB "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_6"); }
  { Lexer l("0b0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_7"); check(t.text=="0b0","literal_text_7"); check(l.lex().isEOF(),"literal_eof_7"); }
  { Lexer l(" 0b0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_7"); }
  { Lexer l("0b10101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_8"); check(t.text=="0b10101","literal_text_8"); check(l.lex().isEOF(),"literal_eof_8"); }
  { Lexer l(" 0b10101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_8"); }
  { Lexer l("0o7"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_9"); check(t.text=="0o7","literal_text_9"); check(l.lex().isEOF(),"literal_eof_9"); }
  { Lexer l(" 0o7 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_9"); }
  { Lexer l("0o755"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_10"); check(t.text=="0o755","literal_text_10"); check(l.lex().isEOF(),"literal_eof_10"); }
  { Lexer l(" 0o755 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_10"); }
  { Lexer l("1.0"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_11"); check(t.text=="1.0","literal_text_11"); check(l.lex().isEOF(),"literal_eof_11"); }
  { Lexer l(" 1.0 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_11"); }
  { Lexer l("3.14159"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_12"); check(t.text=="3.14159","literal_text_12"); check(l.lex().isEOF(),"literal_eof_12"); }
  { Lexer l(" 3.14159 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_12"); }
  { Lexer l("10.25"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_13"); check(t.text=="10.25","literal_text_13"); check(l.lex().isEOF(),"literal_eof_13"); }
  { Lexer l(" 10.25 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_13"); }
  { Lexer l("1e2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_14"); check(t.text=="1e2","literal_text_14"); check(l.lex().isEOF(),"literal_eof_14"); }
  { Lexer l(" 1e2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_14"); }
  { Lexer l("1E2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_15"); check(t.text=="1E2","literal_text_15"); check(l.lex().isEOF(),"literal_eof_15"); }
  { Lexer l(" 1E2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_15"); }
  { Lexer l("1.5e-2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_16"); check(t.text=="1.5e-2","literal_text_16"); check(l.lex().isEOF(),"literal_eof_16"); }
  { Lexer l(" 1.5e-2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_16"); }
  { Lexer l("1.5E+2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_17"); check(t.text=="1.5E+2","literal_text_17"); check(l.lex().isEOF(),"literal_eof_17"); }
  { Lexer l(" 1.5E+2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_17"); }
  { Lexer l("10_000"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_18"); check(t.text=="10_000","literal_text_18"); check(l.lex().isEOF(),"literal_eof_18"); }
  { Lexer l(" 10_000 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_18"); }
  { Lexer l("0xff_ff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_19"); check(t.text=="0xff_ff","literal_text_19"); check(l.lex().isEOF(),"literal_eof_19"); }
  { Lexer l(" 0xff_ff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_19"); }
  { Lexer l("0b1010_0101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_20"); check(t.text=="0b1010_0101","literal_text_20"); check(l.lex().isEOF(),"literal_eof_20"); }
  { Lexer l(" 0b1010_0101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_20"); }
  { Lexer l("0o7_55"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_21"); check(t.text=="0o7_55","literal_text_21"); check(l.lex().isEOF(),"literal_eof_21"); }
  { Lexer l(" 0o7_55 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_21"); }
  { Lexer l("0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_22"); check(t.text=="0","literal_text_22"); check(l.lex().isEOF(),"literal_eof_22"); }
  { Lexer l(" 0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_22"); }
  { Lexer l("1"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_23"); check(t.text=="1","literal_text_23"); check(l.lex().isEOF(),"literal_eof_23"); }
  { Lexer l(" 1 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_23"); }
  { Lexer l("42"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_24"); check(t.text=="42","literal_text_24"); check(l.lex().isEOF(),"literal_eof_24"); }
  { Lexer l(" 42 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_24"); }
  { Lexer l("999999"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_25"); check(t.text=="999999","literal_text_25"); check(l.lex().isEOF(),"literal_eof_25"); }
  { Lexer l(" 999999 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_25"); }
  { Lexer l("0x0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_26"); check(t.text=="0x0","literal_text_26"); check(l.lex().isEOF(),"literal_eof_26"); }
  { Lexer l(" 0x0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_26"); }
  { Lexer l("0xff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_27"); check(t.text=="0xff","literal_text_27"); check(l.lex().isEOF(),"literal_eof_27"); }
  { Lexer l(" 0xff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_27"); }
  { Lexer l("0XAB"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_28"); check(t.text=="0XAB","literal_text_28"); check(l.lex().isEOF(),"literal_eof_28"); }
  { Lexer l(" 0XAB "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_28"); }
  { Lexer l("0b0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_29"); check(t.text=="0b0","literal_text_29"); check(l.lex().isEOF(),"literal_eof_29"); }
  { Lexer l(" 0b0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_29"); }
  { Lexer l("0b10101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_30"); check(t.text=="0b10101","literal_text_30"); check(l.lex().isEOF(),"literal_eof_30"); }
  { Lexer l(" 0b10101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_30"); }
  { Lexer l("0o7"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_31"); check(t.text=="0o7","literal_text_31"); check(l.lex().isEOF(),"literal_eof_31"); }
  { Lexer l(" 0o7 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_31"); }
  { Lexer l("0o755"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_32"); check(t.text=="0o755","literal_text_32"); check(l.lex().isEOF(),"literal_eof_32"); }
  { Lexer l(" 0o755 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_32"); }
  { Lexer l("1.0"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_33"); check(t.text=="1.0","literal_text_33"); check(l.lex().isEOF(),"literal_eof_33"); }
  { Lexer l(" 1.0 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_33"); }
  { Lexer l("3.14159"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_34"); check(t.text=="3.14159","literal_text_34"); check(l.lex().isEOF(),"literal_eof_34"); }
  { Lexer l(" 3.14159 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_34"); }
  { Lexer l("10.25"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_35"); check(t.text=="10.25","literal_text_35"); check(l.lex().isEOF(),"literal_eof_35"); }
  { Lexer l(" 10.25 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_35"); }
  { Lexer l("1e2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_36"); check(t.text=="1e2","literal_text_36"); check(l.lex().isEOF(),"literal_eof_36"); }
  { Lexer l(" 1e2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_36"); }
  { Lexer l("1E2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_37"); check(t.text=="1E2","literal_text_37"); check(l.lex().isEOF(),"literal_eof_37"); }
  { Lexer l(" 1E2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_37"); }
  { Lexer l("1.5e-2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_38"); check(t.text=="1.5e-2","literal_text_38"); check(l.lex().isEOF(),"literal_eof_38"); }
  { Lexer l(" 1.5e-2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_38"); }
  { Lexer l("1.5E+2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_39"); check(t.text=="1.5E+2","literal_text_39"); check(l.lex().isEOF(),"literal_eof_39"); }
  { Lexer l(" 1.5E+2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_39"); }
  { Lexer l("10_000"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_40"); check(t.text=="10_000","literal_text_40"); check(l.lex().isEOF(),"literal_eof_40"); }
  { Lexer l(" 10_000 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_40"); }
  { Lexer l("0xff_ff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_41"); check(t.text=="0xff_ff","literal_text_41"); check(l.lex().isEOF(),"literal_eof_41"); }
  { Lexer l(" 0xff_ff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_41"); }
  { Lexer l("0b1010_0101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_42"); check(t.text=="0b1010_0101","literal_text_42"); check(l.lex().isEOF(),"literal_eof_42"); }
  { Lexer l(" 0b1010_0101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_42"); }
  { Lexer l("0o7_55"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_43"); check(t.text=="0o7_55","literal_text_43"); check(l.lex().isEOF(),"literal_eof_43"); }
  { Lexer l(" 0o7_55 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_43"); }
  { Lexer l("0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_44"); check(t.text=="0","literal_text_44"); check(l.lex().isEOF(),"literal_eof_44"); }
  { Lexer l(" 0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_44"); }
  { Lexer l("1"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_45"); check(t.text=="1","literal_text_45"); check(l.lex().isEOF(),"literal_eof_45"); }
  { Lexer l(" 1 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_45"); }
  { Lexer l("42"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_46"); check(t.text=="42","literal_text_46"); check(l.lex().isEOF(),"literal_eof_46"); }
  { Lexer l(" 42 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_46"); }
  { Lexer l("999999"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_47"); check(t.text=="999999","literal_text_47"); check(l.lex().isEOF(),"literal_eof_47"); }
  { Lexer l(" 999999 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_47"); }
  { Lexer l("0x0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_48"); check(t.text=="0x0","literal_text_48"); check(l.lex().isEOF(),"literal_eof_48"); }
  { Lexer l(" 0x0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_48"); }
  { Lexer l("0xff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_49"); check(t.text=="0xff","literal_text_49"); check(l.lex().isEOF(),"literal_eof_49"); }
  { Lexer l(" 0xff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_49"); }
  { Lexer l("0XAB"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_50"); check(t.text=="0XAB","literal_text_50"); check(l.lex().isEOF(),"literal_eof_50"); }
  { Lexer l(" 0XAB "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_50"); }
  { Lexer l("0b0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_51"); check(t.text=="0b0","literal_text_51"); check(l.lex().isEOF(),"literal_eof_51"); }
  { Lexer l(" 0b0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_51"); }
  { Lexer l("0b10101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_52"); check(t.text=="0b10101","literal_text_52"); check(l.lex().isEOF(),"literal_eof_52"); }
  { Lexer l(" 0b10101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_52"); }
  { Lexer l("0o7"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_53"); check(t.text=="0o7","literal_text_53"); check(l.lex().isEOF(),"literal_eof_53"); }
  { Lexer l(" 0o7 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_53"); }
  { Lexer l("0o755"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_54"); check(t.text=="0o755","literal_text_54"); check(l.lex().isEOF(),"literal_eof_54"); }
  { Lexer l(" 0o755 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_54"); }
  { Lexer l("1.0"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_55"); check(t.text=="1.0","literal_text_55"); check(l.lex().isEOF(),"literal_eof_55"); }
  { Lexer l(" 1.0 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_55"); }
  { Lexer l("3.14159"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_56"); check(t.text=="3.14159","literal_text_56"); check(l.lex().isEOF(),"literal_eof_56"); }
  { Lexer l(" 3.14159 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_56"); }
  { Lexer l("10.25"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_57"); check(t.text=="10.25","literal_text_57"); check(l.lex().isEOF(),"literal_eof_57"); }
  { Lexer l(" 10.25 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_57"); }
  { Lexer l("1e2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_58"); check(t.text=="1e2","literal_text_58"); check(l.lex().isEOF(),"literal_eof_58"); }
  { Lexer l(" 1e2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_58"); }
  { Lexer l("1E2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_59"); check(t.text=="1E2","literal_text_59"); check(l.lex().isEOF(),"literal_eof_59"); }
  { Lexer l(" 1E2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_59"); }
  { Lexer l("1.5e-2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_60"); check(t.text=="1.5e-2","literal_text_60"); check(l.lex().isEOF(),"literal_eof_60"); }
  { Lexer l(" 1.5e-2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_60"); }
  { Lexer l("1.5E+2"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_61"); check(t.text=="1.5E+2","literal_text_61"); check(l.lex().isEOF(),"literal_eof_61"); }
  { Lexer l(" 1.5E+2 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_61"); }
  { Lexer l("10_000"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_62"); check(t.text=="10_000","literal_text_62"); check(l.lex().isEOF(),"literal_eof_62"); }
  { Lexer l(" 10_000 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_62"); }
  { Lexer l("0xff_ff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_63"); check(t.text=="0xff_ff","literal_text_63"); check(l.lex().isEOF(),"literal_eof_63"); }
  { Lexer l(" 0xff_ff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_63"); }
  { Lexer l("0b1010_0101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_64"); check(t.text=="0b1010_0101","literal_text_64"); check(l.lex().isEOF(),"literal_eof_64"); }
  { Lexer l(" 0b1010_0101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_64"); }
  { Lexer l("0o7_55"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_65"); check(t.text=="0o7_55","literal_text_65"); check(l.lex().isEOF(),"literal_eof_65"); }
  { Lexer l(" 0o7_55 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_65"); }
  { Lexer l("0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_66"); check(t.text=="0","literal_text_66"); check(l.lex().isEOF(),"literal_eof_66"); }
  { Lexer l(" 0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_66"); }
  { Lexer l("1"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_67"); check(t.text=="1","literal_text_67"); check(l.lex().isEOF(),"literal_eof_67"); }
  { Lexer l(" 1 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_67"); }
  { Lexer l("42"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_68"); check(t.text=="42","literal_text_68"); check(l.lex().isEOF(),"literal_eof_68"); }
  { Lexer l(" 42 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_68"); }
  { Lexer l("999999"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_69"); check(t.text=="999999","literal_text_69"); check(l.lex().isEOF(),"literal_eof_69"); }
  { Lexer l(" 999999 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_69"); }
  { Lexer l("0x0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_70"); check(t.text=="0x0","literal_text_70"); check(l.lex().isEOF(),"literal_eof_70"); }
  { Lexer l(" 0x0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_70"); }
  { Lexer l("0xff"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_71"); check(t.text=="0xff","literal_text_71"); check(l.lex().isEOF(),"literal_eof_71"); }
  { Lexer l(" 0xff "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_71"); }
  { Lexer l("0XAB"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_72"); check(t.text=="0XAB","literal_text_72"); check(l.lex().isEOF(),"literal_eof_72"); }
  { Lexer l(" 0XAB "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_72"); }
  { Lexer l("0b0"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_73"); check(t.text=="0b0","literal_text_73"); check(l.lex().isEOF(),"literal_eof_73"); }
  { Lexer l(" 0b0 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_73"); }
  { Lexer l("0b10101"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_74"); check(t.text=="0b10101","literal_text_74"); check(l.lex().isEOF(),"literal_eof_74"); }
  { Lexer l(" 0b10101 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_74"); }
  { Lexer l("0o7"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_75"); check(t.text=="0o7","literal_text_75"); check(l.lex().isEOF(),"literal_eof_75"); }
  { Lexer l(" 0o7 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_75"); }
  { Lexer l("0o755"); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_76"); check(t.text=="0o755","literal_text_76"); check(l.lex().isEOF(),"literal_eof_76"); }
  { Lexer l(" 0o755 "); auto t=l.lex(); check(t.kind==TokenKind::IntegerLiteral,"literal_space_76"); }
  { Lexer l("1.0"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_77"); check(t.text=="1.0","literal_text_77"); check(l.lex().isEOF(),"literal_eof_77"); }
  { Lexer l(" 1.0 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_77"); }
  { Lexer l("3.14159"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_78"); check(t.text=="3.14159","literal_text_78"); check(l.lex().isEOF(),"literal_eof_78"); }
  { Lexer l(" 3.14159 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_78"); }
  { Lexer l("10.25"); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_79"); check(t.text=="10.25","literal_text_79"); check(l.lex().isEOF(),"literal_eof_79"); }
  { Lexer l(" 10.25 "); auto t=l.lex(); check(t.kind==TokenKind::FloatingLiteral,"literal_space_79"); }

  return failures?1:0;
}
