#include "hyper/lib/Parse/Lexer.h"
#include <iostream>
#include <string>
using namespace hyper::parse;
static int failures=0;
static void check(bool v,const std::string&n){if(!v){std::cerr<<"FAIL "<<n<<"\n";++failures;}}
int main(){
  { Lexer l("function"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_0_function"); check(t.text=="function","spelling_0_function"); check(l.lex().isEOF(),"eof_0_function"); }
  { Lexer l(" function "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_0"); }
  { Lexer l("var"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_1_var"); check(t.text=="var","spelling_1_var"); check(l.lex().isEOF(),"eof_1_var"); }
  { Lexer l(" var "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_1"); }
  { Lexer l("const"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_2_const"); check(t.text=="const","spelling_2_const"); check(l.lex().isEOF(),"eof_2_const"); }
  { Lexer l(" const "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_2"); }
  { Lexer l("struct"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_3_struct"); check(t.text=="struct","spelling_3_struct"); check(l.lex().isEOF(),"eof_3_struct"); }
  { Lexer l(" struct "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_3"); }
  { Lexer l("class"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_4_class"); check(t.text=="class","spelling_4_class"); check(l.lex().isEOF(),"eof_4_class"); }
  { Lexer l(" class "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_4"); }
  { Lexer l("enum"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_5_enum"); check(t.text=="enum","spelling_5_enum"); check(l.lex().isEOF(),"eof_5_enum"); }
  { Lexer l(" enum "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_5"); }
  { Lexer l("protocol"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_6_protocol"); check(t.text=="protocol","spelling_6_protocol"); check(l.lex().isEOF(),"eof_6_protocol"); }
  { Lexer l(" protocol "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_6"); }
  { Lexer l("extension"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_7_extension"); check(t.text=="extension","spelling_7_extension"); check(l.lex().isEOF(),"eof_7_extension"); }
  { Lexer l(" extension "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_7"); }
  { Lexer l("type"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_8_type"); check(t.text=="type","spelling_8_type"); check(l.lex().isEOF(),"eof_8_type"); }
  { Lexer l(" type "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_8"); }
  { Lexer l("typealias"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_9_typealias"); check(t.text=="typealias","spelling_9_typealias"); check(l.lex().isEOF(),"eof_9_typealias"); }
  { Lexer l(" typealias "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_9"); }
  { Lexer l("template"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_10_template"); check(t.text=="template","spelling_10_template"); check(l.lex().isEOF(),"eof_10_template"); }
  { Lexer l(" template "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_10"); }
  { Lexer l("typename"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_11_typename"); check(t.text=="typename","spelling_11_typename"); check(l.lex().isEOF(),"eof_11_typename"); }
  { Lexer l(" typename "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_11"); }
  { Lexer l("operator"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_12_operator"); check(t.text=="operator","spelling_12_operator"); check(l.lex().isEOF(),"eof_12_operator"); }
  { Lexer l(" operator "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_12"); }
  { Lexer l("namespace"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_13_namespace"); check(t.text=="namespace","spelling_13_namespace"); check(l.lex().isEOF(),"eof_13_namespace"); }
  { Lexer l(" namespace "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_13"); }
  { Lexer l("module"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_14_module"); check(t.text=="module","spelling_14_module"); check(l.lex().isEOF(),"eof_14_module"); }
  { Lexer l(" module "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_14"); }
  { Lexer l("init"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_15_init"); check(t.text=="init","spelling_15_init"); check(l.lex().isEOF(),"eof_15_init"); }
  { Lexer l(" init "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_15"); }
  { Lexer l("deinit"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_16_deinit"); check(t.text=="deinit","spelling_16_deinit"); check(l.lex().isEOF(),"eof_16_deinit"); }
  { Lexer l(" deinit "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_16"); }
  { Lexer l("self"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_17_self"); check(t.text=="self","spelling_17_self"); check(l.lex().isEOF(),"eof_17_self"); }
  { Lexer l(" self "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_17"); }
  { Lexer l("super"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_18_super"); check(t.text=="super","spelling_18_super"); check(l.lex().isEOF(),"eof_18_super"); }
  { Lexer l(" super "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_18"); }
  { Lexer l("new"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_19_new"); check(t.text=="new","spelling_19_new"); check(l.lex().isEOF(),"eof_19_new"); }
  { Lexer l(" new "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_19"); }
  { Lexer l("get"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_20_get"); check(t.text=="get","spelling_20_get"); check(l.lex().isEOF(),"eof_20_get"); }
  { Lexer l(" get "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_20"); }
  { Lexer l("set"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_21_set"); check(t.text=="set","spelling_21_set"); check(l.lex().isEOF(),"eof_21_set"); }
  { Lexer l(" set "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_21"); }
  { Lexer l("if"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_22_if"); check(t.text=="if","spelling_22_if"); check(l.lex().isEOF(),"eof_22_if"); }
  { Lexer l(" if "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_22"); }
  { Lexer l("elseif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_23_elseif"); check(t.text=="elseif","spelling_23_elseif"); check(l.lex().isEOF(),"eof_23_elseif"); }
  { Lexer l(" elseif "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_23"); }
  { Lexer l("else"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_24_else"); check(t.text=="else","spelling_24_else"); check(l.lex().isEOF(),"eof_24_else"); }
  { Lexer l(" else "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_24"); }
  { Lexer l("endif"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_25_endif"); check(t.text=="endif","spelling_25_endif"); check(l.lex().isEOF(),"eof_25_endif"); }
  { Lexer l(" endif "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_25"); }
  { Lexer l("switch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_26_switch"); check(t.text=="switch","spelling_26_switch"); check(l.lex().isEOF(),"eof_26_switch"); }
  { Lexer l(" switch "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_26"); }
  { Lexer l("case"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_27_case"); check(t.text=="case","spelling_27_case"); check(l.lex().isEOF(),"eof_27_case"); }
  { Lexer l(" case "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_27"); }
  { Lexer l("default"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_28_default"); check(t.text=="default","spelling_28_default"); check(l.lex().isEOF(),"eof_28_default"); }
  { Lexer l(" default "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_28"); }
  { Lexer l("while"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_29_while"); check(t.text=="while","spelling_29_while"); check(l.lex().isEOF(),"eof_29_while"); }
  { Lexer l(" while "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_29"); }
  { Lexer l("loop"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_30_loop"); check(t.text=="loop","spelling_30_loop"); check(l.lex().isEOF(),"eof_30_loop"); }
  { Lexer l(" loop "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_30"); }
  { Lexer l("do"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_31_do"); check(t.text=="do","spelling_31_do"); check(l.lex().isEOF(),"eof_31_do"); }
  { Lexer l(" do "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_31"); }
  { Lexer l("for"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_32_for"); check(t.text=="for","spelling_32_for"); check(l.lex().isEOF(),"eof_32_for"); }
  { Lexer l(" for "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_32"); }
  { Lexer l("in"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_33_in"); check(t.text=="in","spelling_33_in"); check(l.lex().isEOF(),"eof_33_in"); }
  { Lexer l(" in "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_33"); }
  { Lexer l("break"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_34_break"); check(t.text=="break","spelling_34_break"); check(l.lex().isEOF(),"eof_34_break"); }
  { Lexer l(" break "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_34"); }
  { Lexer l("continue"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_35_continue"); check(t.text=="continue","spelling_35_continue"); check(l.lex().isEOF(),"eof_35_continue"); }
  { Lexer l(" continue "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_35"); }
  { Lexer l("return"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_36_return"); check(t.text=="return","spelling_36_return"); check(l.lex().isEOF(),"eof_36_return"); }
  { Lexer l(" return "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_36"); }
  { Lexer l("throw"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_37_throw"); check(t.text=="throw","spelling_37_throw"); check(l.lex().isEOF(),"eof_37_throw"); }
  { Lexer l(" throw "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_37"); }
  { Lexer l("try"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_38_try"); check(t.text=="try","spelling_38_try"); check(l.lex().isEOF(),"eof_38_try"); }
  { Lexer l(" try "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_38"); }
  { Lexer l("catch"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_39_catch"); check(t.text=="catch","spelling_39_catch"); check(l.lex().isEOF(),"eof_39_catch"); }
  { Lexer l(" catch "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_39"); }
  { Lexer l("finally"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_40_finally"); check(t.text=="finally","spelling_40_finally"); check(l.lex().isEOF(),"eof_40_finally"); }
  { Lexer l(" finally "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_40"); }
  { Lexer l("defer"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_41_defer"); check(t.text=="defer","spelling_41_defer"); check(l.lex().isEOF(),"eof_41_defer"); }
  { Lexer l(" defer "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_41"); }
  { Lexer l("error"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_42_error"); check(t.text=="error","spelling_42_error"); check(l.lex().isEOF(),"eof_42_error"); }
  { Lexer l(" error "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_42"); }
  { Lexer l("panic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_43_panic"); check(t.text=="panic","spelling_43_panic"); check(l.lex().isEOF(),"eof_43_panic"); }
  { Lexer l(" panic "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_43"); }
  { Lexer l("bool"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_44_bool"); check(t.text=="bool","spelling_44_bool"); check(l.lex().isEOF(),"eof_44_bool"); }
  { Lexer l(" bool "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_44"); }
  { Lexer l("int"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_45_int"); check(t.text=="int","spelling_45_int"); check(l.lex().isEOF(),"eof_45_int"); }
  { Lexer l(" int "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_45"); }
  { Lexer l("uint"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_46_uint"); check(t.text=="uint","spelling_46_uint"); check(l.lex().isEOF(),"eof_46_uint"); }
  { Lexer l(" uint "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_46"); }
  { Lexer l("int8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_47_int8"); check(t.text=="int8","spelling_47_int8"); check(l.lex().isEOF(),"eof_47_int8"); }
  { Lexer l(" int8 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_47"); }
  { Lexer l("int16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_48_int16"); check(t.text=="int16","spelling_48_int16"); check(l.lex().isEOF(),"eof_48_int16"); }
  { Lexer l(" int16 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_48"); }
  { Lexer l("int32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_49_int32"); check(t.text=="int32","spelling_49_int32"); check(l.lex().isEOF(),"eof_49_int32"); }
  { Lexer l(" int32 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_49"); }
  { Lexer l("int64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_50_int64"); check(t.text=="int64","spelling_50_int64"); check(l.lex().isEOF(),"eof_50_int64"); }
  { Lexer l(" int64 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_50"); }
  { Lexer l("uint8"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_51_uint8"); check(t.text=="uint8","spelling_51_uint8"); check(l.lex().isEOF(),"eof_51_uint8"); }
  { Lexer l(" uint8 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_51"); }
  { Lexer l("uint16"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_52_uint16"); check(t.text=="uint16","spelling_52_uint16"); check(l.lex().isEOF(),"eof_52_uint16"); }
  { Lexer l(" uint16 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_52"); }
  { Lexer l("uint32"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_53_uint32"); check(t.text=="uint32","spelling_53_uint32"); check(l.lex().isEOF(),"eof_53_uint32"); }
  { Lexer l(" uint32 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_53"); }
  { Lexer l("uint64"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_54_uint64"); check(t.text=="uint64","spelling_54_uint64"); check(l.lex().isEOF(),"eof_54_uint64"); }
  { Lexer l(" uint64 "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_54"); }
  { Lexer l("float"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_55_float"); check(t.text=="float","spelling_55_float"); check(l.lex().isEOF(),"eof_55_float"); }
  { Lexer l(" float "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_55"); }
  { Lexer l("double"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_56_double"); check(t.text=="double","spelling_56_double"); check(l.lex().isEOF(),"eof_56_double"); }
  { Lexer l(" double "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_56"); }
  { Lexer l("byte"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_57_byte"); check(t.text=="byte","spelling_57_byte"); check(l.lex().isEOF(),"eof_57_byte"); }
  { Lexer l(" byte "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_57"); }
  { Lexer l("char"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_58_char"); check(t.text=="char","spelling_58_char"); check(l.lex().isEOF(),"eof_58_char"); }
  { Lexer l(" char "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_58"); }
  { Lexer l("string"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_59_string"); check(t.text=="string","spelling_59_string"); check(l.lex().isEOF(),"eof_59_string"); }
  { Lexer l(" string "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_59"); }
  { Lexer l("void"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_60_void"); check(t.text=="void","spelling_60_void"); check(l.lex().isEOF(),"eof_60_void"); }
  { Lexer l(" void "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_60"); }
  { Lexer l("nil"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_61_nil"); check(t.text=="nil","spelling_61_nil"); check(l.lex().isEOF(),"eof_61_nil"); }
  { Lexer l(" nil "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_61"); }
  { Lexer l("public"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_62_public"); check(t.text=="public","spelling_62_public"); check(l.lex().isEOF(),"eof_62_public"); }
  { Lexer l(" public "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_62"); }
  { Lexer l("private"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_63_private"); check(t.text=="private","spelling_63_private"); check(l.lex().isEOF(),"eof_63_private"); }
  { Lexer l(" private "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_63"); }
  { Lexer l("protected"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_64_protected"); check(t.text=="protected","spelling_64_protected"); check(l.lex().isEOF(),"eof_64_protected"); }
  { Lexer l(" protected "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_64"); }
  { Lexer l("internal"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_65_internal"); check(t.text=="internal","spelling_65_internal"); check(l.lex().isEOF(),"eof_65_internal"); }
  { Lexer l(" internal "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_65"); }
  { Lexer l("static"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_66_static"); check(t.text=="static","spelling_66_static"); check(l.lex().isEOF(),"eof_66_static"); }
  { Lexer l(" static "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_66"); }
  { Lexer l("extern"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_67_extern"); check(t.text=="extern","spelling_67_extern"); check(l.lex().isEOF(),"eof_67_extern"); }
  { Lexer l(" extern "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_67"); }
  { Lexer l("inline"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_68_inline"); check(t.text=="inline","spelling_68_inline"); check(l.lex().isEOF(),"eof_68_inline"); }
  { Lexer l(" inline "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_68"); }
  { Lexer l("volatile"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_69_volatile"); check(t.text=="volatile","spelling_69_volatile"); check(l.lex().isEOF(),"eof_69_volatile"); }
  { Lexer l(" volatile "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_69"); }
  { Lexer l("sizeof"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_70_sizeof"); check(t.text=="sizeof","spelling_70_sizeof"); check(l.lex().isEOF(),"eof_70_sizeof"); }
  { Lexer l(" sizeof "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_70"); }
  { Lexer l("async"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_71_async"); check(t.text=="async","spelling_71_async"); check(l.lex().isEOF(),"eof_71_async"); }
  { Lexer l(" async "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_71"); }
  { Lexer l("await"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_72_await"); check(t.text=="await","spelling_72_await"); check(l.lex().isEOF(),"eof_72_await"); }
  { Lexer l(" await "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_72"); }
  { Lexer l("task"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_73_task"); check(t.text=="task","spelling_73_task"); check(l.lex().isEOF(),"eof_73_task"); }
  { Lexer l(" task "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_73"); }
  { Lexer l("actor"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_74_actor"); check(t.text=="actor","spelling_74_actor"); check(l.lex().isEOF(),"eof_74_actor"); }
  { Lexer l(" actor "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_74"); }
  { Lexer l("parallel"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_75_parallel"); check(t.text=="parallel","spelling_75_parallel"); check(l.lex().isEOF(),"eof_75_parallel"); }
  { Lexer l(" parallel "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_75"); }
  { Lexer l("atomic"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_76_atomic"); check(t.text=="atomic","spelling_76_atomic"); check(l.lex().isEOF(),"eof_76_atomic"); }
  { Lexer l(" atomic "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_76"); }
  { Lexer l("input"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_77_input"); check(t.text=="input","spelling_77_input"); check(l.lex().isEOF(),"eof_77_input"); }
  { Lexer l(" input "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_77"); }
  { Lexer l("output"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_78_output"); check(t.text=="output","spelling_78_output"); check(l.lex().isEOF(),"eof_78_output"); }
  { Lexer l(" output "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_78"); }
  { Lexer l("message"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_79_message"); check(t.text=="message","spelling_79_message"); check(l.lex().isEOF(),"eof_79_message"); }
  { Lexer l(" message "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_79"); }
  { Lexer l("show"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_80_show"); check(t.text=="show","spelling_80_show"); check(l.lex().isEOF(),"eof_80_show"); }
  { Lexer l(" show "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_80"); }
  { Lexer l("getData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_81_getData"); check(t.text=="getData","spelling_81_getData"); check(l.lex().isEOF(),"eof_81_getData"); }
  { Lexer l(" getData "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_81"); }
  { Lexer l("createData"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_82_createData"); check(t.text=="createData","spelling_82_createData"); check(l.lex().isEOF(),"eof_82_createData"); }
  { Lexer l(" createData "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_82"); }
  { Lexer l("from"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_83_from"); check(t.text=="from","spelling_83_from"); check(l.lex().isEOF(),"eof_83_from"); }
  { Lexer l(" from "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_83"); }
  { Lexer l("import"); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"keyword_84_import"); check(t.text=="import","spelling_84_import"); check(l.lex().isEOF(),"eof_84_import"); }
  { Lexer l(" import "); auto t=l.lex(); check(t.kind==TokenKind::Keyword,"space_84"); }

  return failures?1:0;
}
