#include "hyper/Lexer.h"
#include <cctype>
#include <cstring>
#include <unordered_map>

namespace hyper {
namespace {
using K=TokenKind;
const std::unordered_map<std::string_view,K> keywords={
{"if",K::KwIf},{"else",K::KwElse},{"while",K::KwWhile},{"do",K::KwDo},{"for",K::KwFor},{"in",K::KwIn},{"func",K::KwFunc},{"var",K::KwVar},{"let",K::KwLet},{"const",K::KwConst},{"return",K::KwReturn},{"struct",K::KwStruct},{"class",K::KwClass},{"enum",K::KwEnum},{"protocol",K::KwProtocol},{"extension",K::KwExtension},{"import",K::KwImport},{"module",K::KwModule},{"package",K::KwPackage},{"namespace",K::KwNamespace},{"public",K::KwPublic},{"private",K::KwPrivate},{"internal",K::KwInternal},{"protected",K::KwProtected},{"static",K::KwStatic},{"final",K::KwFinal},{"override",K::KwOverride},{"init",K::KwInit},{"deinit",K::KwDeinit},{"defer",K::KwDefer},{"break",K::KwBreak},{"continue",K::KwContinue},{"true",K::KwTrue},{"false",K::KwFalse},{"nil",K::KwNil},{"and",K::KwAnd},{"or",K::KwOr},{"not",K::KwNot},{"move",K::KwMove},{"borrow",K::KwBorrow},{"consume",K::KwConsume},{"copy",K::KwCopy},{"own",K::KwOwn},{"shared",K::KwShared},{"weak",K::KwWeak},{"unowned",K::KwUnowned},{"auto",K::KwAuto},{"type",K::KwType},{"typealias",K::KwTypealias},{"associatedtype",K::KwAssociatedType},{"int",K::KwInt},{"float",K::KwFloat},{"bool",K::KwBool},{"string",K::KwString},{"bytes",K::KwBytes},{"num",K::KwNum},{"guard",K::KwGuard},{"switch",K::KwSwitch},{"case",K::KwCase},{"default",K::KwDefault},{"throw",K::KwThrow},{"throws",K::KwThrows},{"catch",K::KwCatch},{"async",K::KwAsync},{"await",K::KwAwait},{"task",K::KwTask},{"actor",K::KwActor},{"some",K::KwSome},{"any",K::KwAny},{"self",K::KwSelf},{"where",K::KwWhere},{"get",K::KwGet},{"set",K::KwSet},{"mutating",K::KwMutating},{"operator",K::KwOperator},{"subscript",K::KwSubscript},{"yield",K::KwYield},{"macro",K::KwMacro},{"attribute",K::KwAttribute},{"observe",K::KwObserve},{"synchronize",K::KwSynchronize},{"compile",K::KwCompile},{"extern",K::KwExtern},{"output",K::KwOutput},{"input",K::KwInput},{"panic",K::KwPanic},{"loop",K::KwLoop},{"endloop",K::KwEndLoop},{"then",K::KwThen},{"endif",K::KwEndIf},{"source",K::KwSource},{"file",K::KwFile},{"function",K::KwFunction},{"property",K::KwProperty},{"event",K::KwEvent},{"signal",K::KwSignal},{"detached",K::KwDetached},{"isolated",K::KwIsolated},{"nonisolated",K::KwNonisolated},{"sendable",K::KwSendable}};
struct Op{std::string_view text;K kind;};
const Op ops[]={{">>=",K::ShiftRightEqual},{"<<=",K::ShiftLeftEqual},{"===",K::EqualEqual},{"!==",K::NotEqual},{"...",K::ClosedRange},{"..<",K::Range},{"??",K::QuestionQuestion},{"=>",K::FatArrow},{"->",K::Arrow},{"==",K::EqualEqual},{"!=",K::NotEqual},{">=",K::GreaterEqual},{"<=",K::LessEqual},{"+=",K::PlusEqual},{"-=",K::MinusEqual},{"*=",K::StarEqual},{"/=",K::SlashEqual},{"%=",K::PercentEqual},{"&=",K::AmpersandEqual},{"|=",K::PipeEqual},{"^=",K::CaretEqual},{"<<",K::ShiftLeft},{">>",K::ShiftRight},{"&&",K::AndAnd},{"||",K::OrOr},{"~=",K::TildeEqual},{"**",K::Power}};
bool isIdStart(char c){return std::isalpha((unsigned char)c)||c=='_';}
bool isIdPart(char c){return std::isalnum((unsigned char)c)||c=='_';}
bool isOp(char c){return std::strchr("+-*/%=&|^~!?<>",c)!=nullptr;}
}
Lexer::Lexer(std::string_view s):source_(s){}
char Lexer::peek(std::size_t d)const noexcept{return current_+d<source_.size()?source_[current_+d]:'\0';}
char Lexer::advance()noexcept{char c=peek();if(!c)return c;++current_;if(c=='\n'){++line_;column_=1;atStartOfLine_=true;}else{++column_;if(c!='\r'&&c!=' '&&c!='\t')atStartOfLine_=false;}return c;}
bool Lexer::match(char c)noexcept{if(peek()!=c)return false;advance();return true;}
bool Lexer::startsWith(std::string_view s)const noexcept{return current_+s.size()<=source_.size()&&source_.substr(current_,s.size())==s;}
SourceLocation Lexer::locationFromOffset(std::size_t p)const{SourceLocation l{};l.line=1;l.column=1;for(std::size_t i=0;i<p&&i<source_.size();++i){l.offset=i+1;if(source_[i]=='\n'){++l.line;l.column=1;}else ++l.column;}return l;}
Token Lexer::makeToken(K k,std::size_t s,SourceLocation l,bool bad)const{Token t;t.kind=k;t.text=std::string(source_.substr(s,current_-s));t.location=l;t.malformed=bad;t.atStartOfLine=l.column==1;t.hasLeadingComment=hadLeadingComment_;return t;}
K Lexer::keywordKind(std::string_view s)noexcept{auto i=keywords.find(s);return i==keywords.end()?K::Identifier:i->second;}
K Lexer::punctuationKind(std::string_view s)noexcept{if(s==".")return K::Dot;if(s==",")return K::Comma;if(s==":")return K::Colon;if(s=="::")return K::DoubleColon;if(s==";")return K::Semicolon;if(s=="\\")return K::Backslash;if(s=="(")return K::LeftParen;if(s==")")return K::RightParen;if(s=="{")return K::LeftBrace;if(s=="}")return K::RightBrace;if(s=="[")return K::LeftBracket;if(s=="]")return K::RightBracket;return K::Unknown;}
K Lexer::operatorKind(std::string_view s)noexcept{for(const auto&o:ops)if(o.text==s)return o.kind;if(s=="+")return K::Plus;if(s=="-")return K::Minus;if(s=="*")return K::Star;if(s=="/")return K::Slash;if(s=="%")return K::Percent;if(s=="&")return K::Ampersand;if(s=="|")return K::Pipe;if(s=="^")return K::Caret;if(s=="~")return K::Tilde;if(s=="!")return K::Bang;if(s=="?")return K::Question;if(s=="=")return K::Equal;if(s==">")return K::Greater;if(s=="<")return K::Less;return K::Unknown;}
Token Lexer::lexIdentifierOrKeyword(){auto s=current_;auto l=currentLocation();while(isIdPart(peek()))advance();return makeToken(keywordKind(source_.substr(s,current_-s)),s,l);}
Token Lexer::lexEscapedIdentifier(){auto s=current_;auto l=currentLocation();advance();while(peek()&&peek()!='`')advance();bool bad=!match('`');return makeToken(bad?K::Unknown:K::EscapedIdentifier,s,l,bad);}
Token Lexer::lexDollarIdentifier(){auto s=current_;auto l=currentLocation();advance();while(isIdPart(peek()))advance();return makeToken(K::DollarIdentifier,s,l);}
Token Lexer::lexNumber(){auto s=current_;auto l=currentLocation();NumericLiteralInfo n;K k=K::IntegerLiteral;if(startsWith("0b")||startsWith("0B")){n.base=NumberBase::Binary;k=K::BinaryIntegerLiteral;advance();advance();while(peek()=='0'||peek()=='1'||peek()=='_')advance();}else if(startsWith("0o")||startsWith("0O")){n.base=NumberBase::Octal;k=K::OctalIntegerLiteral;advance();advance();while((peek()>='0'&&peek()<='7')||peek()=='_')advance();}else if(startsWith("0x")||startsWith("0X")){n.base=NumberBase::Hexadecimal;k=K::HexIntegerLiteral;advance();advance();while(std::isxdigit((unsigned char)peek())||peek()=='_')advance();if(peek()=='.'){k=K::HexFloatLiteral;n.hasDecimalPoint=true;advance();while(std::isxdigit((unsigned char)peek())||peek()=='_')advance();}}else{while(std::isdigit((unsigned char)peek())||peek()=='_')advance();if(peek()=='.'&&std::isdigit((unsigned char)peek(1))){k=K::FloatLiteral;n.hasDecimalPoint=true;advance();while(std::isdigit((unsigned char)peek())||peek()=='_')advance();}if(peek()=='e'||peek()=='E'){k=K::FloatLiteral;n.hasExponent=true;advance();if(peek()=='+'||peek()=='-')advance();while(std::isdigit((unsigned char)peek())||peek()=='_')advance();}}n.hasSeparators=source_.substr(s,current_-s).find('_')!=std::string_view::npos;Token t=makeToken(k,s,l);t.numeric=n;return t;}
Token Lexer::lexString(){auto s=current_;auto l=currentLocation();bool multi=startsWith("\"\"\"");StringLiteralInfo i;i.kind=multi?StringKind::Multiline:StringKind::Normal;if(multi){advance();advance();advance();}else advance();bool closed=false;while(peek()){if(multi&&startsWith("\"\"\"")){advance();advance();advance();closed=true;break;}if(!multi&&peek()=='"'){advance();closed=true;break;}if(peek()=='\\'){i.hasEscapes=true;advance();if(peek())advance();continue;}if(peek()=='$'&&peek(1)=='(')i.hasInterpolation=true;advance();}Token t=makeToken(closed?(multi?K::MultilineStringLiteral:K::StringLiteral):K::Unknown,s,l,!closed);t.string=i;if(!closed)diagnoseError(l,"unterminated string literal");return t;}
Token Lexer::lexCharacter(){auto s=current_;auto l=currentLocation();advance();if(peek()=='\\'){advance();if(peek())advance();}else if(peek()&&peek()!='\n'&&peek()!='\'')advance();bool bad=!match('\'');return makeToken(bad?K::Unknown:K::CharacterLiteral,s,l,bad);}
Token Lexer::lexRawString(unsigned){return lexString();}
Token Lexer::lexRegex(){return lexOperator();}
bool Lexer::lexLineComment(){if(!startsWith("//"))return false;auto s=current_;auto l=currentLocation();advance();advance();while(peek()&&peek()!='\n')advance();hadLeadingComment_=true;if(keepComments_)lookaheadBuffer_.push_back(makeToken(K::Comment,s,l));return true;}
bool Lexer::lexBlockComment(){if(!startsWith("/*"))return false;auto s=current_;auto l=currentLocation();advance();advance();while(peek()&&!startsWith("*/"))advance();bool bad=!peek();if(!bad){advance();advance();}hadLeadingComment_=true;if(keepComments_)lookaheadBuffer_.push_back(makeToken(bad?K::Unknown:K::Comment,s,l,bad));if(bad)diagnoseError(l,"unterminated block comment");return true;}
bool Lexer::lexHashbang(){if(current_!=0||!allowHashbang_||!startsWith("#!"))return false;auto s=current_;auto l=currentLocation();while(peek()&&peek()!='\n')advance();if(keepComments_)lookaheadBuffer_.push_back(makeToken(K::Hashbang,s,l));return true;}
bool Lexer::lexConflictMarker(){if(!atStartOfLine_)return false;if(startsWith("<<<<<<<")||startsWith("=======")||startsWith(">>>>>>>")){auto s=current_;auto l=currentLocation();while(peek()&&peek()!='\n')advance();lookaheadBuffer_.push_back(makeToken(K::ConflictMarker,s,l));return true;}return false;}
void Lexer::consumeTrivia(){hadLeadingComment_=false;for(;;){while(std::isspace((unsigned char)peek()))advance();if(lexHashbang()||lexLineComment()||lexBlockComment()||lexConflictMarker())continue;break;}}
Token Lexer::lexOperator(){auto s=current_;auto l=currentLocation();for(const auto&o:ops)if(startsWith(o.text)){for(char c:o.text)advance();Token t=makeToken(o.kind,s,l);t.binding=classifyOperatorBinding(source_,s,current_);return t;}advance();Token t=makeToken(operatorKind(source_.substr(s,1)),s,l);t.binding=classifyOperatorBinding(source_,s,current_);return t;}
Token Lexer::lexDirective(){auto s=current_;auto l=currentLocation();advance();while(isIdPart(peek())||peek()=='-')advance();return makeToken(K::Directive,s,l);}
Token Lexer::lexHashConstruct(){if(peek(1)&&isIdStart(peek(1)))return lexDirective();auto s=current_;auto l=currentLocation();advance();return makeToken(K::Hash,s,l);}
Token Lexer::lexUnknown(){auto s=current_;auto l=currentLocation();char c=advance();diagnoseError(l,std::string("unexpected character '")+c+"'");return makeToken(K::Unknown,s,l,true);}
Token Lexer::next(){if(!lookaheadBuffer_.empty()){Token t=std::move(lookaheadBuffer_.front());lookaheadBuffer_.erase(lookaheadBuffer_.begin());return t;}consumeTrivia();auto s=current_;auto l=currentLocation();char c=peek();if(!c)return makeToken(K::EndOfFile,s,l);if(isIdStart(c))return lexIdentifierOrKeyword();if(c=='`')return lexEscapedIdentifier();if(c=='$')return lexDollarIdentifier();if(std::isdigit((unsigned char)c))return lexNumber();if(c=='"')return lexString();if(c=='\'')return lexCharacter();if(c=='#')return lexHashConstruct();if(c=='@'){advance();return makeToken(K::AtSign,s,l);}if(isOp(c))return lexOperator();K p=punctuationKind(std::string_view(&c,1));if(p!=K::Unknown){advance();return makeToken(p,s,l);}return lexUnknown();}
Token Lexer::peek(){return lookahead(0);}Token Lexer::lookahead(std::size_t d){while(lookaheadBuffer_.size()<=d){Token t=next();lookaheadBuffer_.push_back(t);if(t.kind==K::EndOfFile)break;}return lookaheadBuffer_[d<lookaheadBuffer_.size()?d:lookaheadBuffer_.size()-1];}
std::vector<Token> Lexer::tokenize(){std::vector<Token> r;for(;;){Token t=next();r.push_back(t);if(t.kind==K::EndOfFile)break;}return r;}
void Lexer::reset(){current_=0;line_=1;column_=1;atStartOfLine_=true;hadLeadingComment_=false;lookaheadBuffer_.clear();diagnostics_.clear();}
void Lexer::setKeepComments(bool v){keepComments_=v;}void Lexer::setAllowHashbang(bool v){allowHashbang_=v;}void Lexer::setAllowRegexLiterals(bool v){allowRegexLiterals_=v;}void Lexer::setTreatEditorPlaceholdersAsTokens(bool v){treatEditorPlaceholdersAsTokens_=v;}
bool Lexer::keepComments()const noexcept{return keepComments_;}bool Lexer::allowHashbang()const noexcept{return allowHashbang_;}bool Lexer::allowRegexLiterals()const noexcept{return allowRegexLiterals_;}bool Lexer::atEnd()const noexcept{return current_>=source_.size();}std::size_t Lexer::currentOffset()const noexcept{return current_;}SourceLocation Lexer::currentLocation()const noexcept{return {current_,line_,column_};}const std::vector<LexerDiagnostic>& Lexer::diagnostics()const noexcept{return diagnostics_;}void Lexer::clearDiagnostics(){diagnostics_.clear();}
void Lexer::diagnose(LexerDiagnostic::Severity s,SourceLocation l,std::string m,std::string r){diagnostics_.push_back({s,l,std::move(m),std::move(r)});}void Lexer::diagnoseError(SourceLocation l,std::string m,std::string r){diagnose(LexerDiagnostic::Severity::Error,l,std::move(m),std::move(r));}void Lexer::diagnoseWarning(SourceLocation l,std::string m,std::string r){diagnose(LexerDiagnostic::Severity::Warning,l,std::move(m),std::move(r));}
bool Lexer::isWhitespaceAt(std::size_t p)const noexcept{return p<source_.size()&&std::isspace((unsigned char)source_[p]);}bool Lexer::isLineBreakAt(std::size_t p)const noexcept{return p<source_.size()&&(source_[p]=='\n'||source_[p]=='\r');}
bool Lexer::isASCIIIdentifierStart(char c)noexcept{return isIdStart(c);}bool Lexer::isASCIIIdentifierContinue(char c)noexcept{return isIdPart(c);}bool Lexer::isASCIIDigit(char c)noexcept{return std::isdigit((unsigned char)c)!=0;}bool Lexer::isASCIIHexDigit(char c)noexcept{return std::isxdigit((unsigned char)c)!=0;}bool Lexer::isASCIIOctalDigit(char c)noexcept{return c>='0'&&c<='7';}bool Lexer::isASCIIWhitespace(char c)noexcept{return std::isspace((unsigned char)c)!=0;}bool Lexer::isPrintableASCII(char c)noexcept{return c>=32&&c<127;}
bool Lexer::isUnicodeIdentifierStart(std::uint32_t c)noexcept{return c>=128;}bool Lexer::isUnicodeIdentifierContinue(std::uint32_t c)noexcept{return c>=128||c=='_';}bool Lexer::isForbiddenIdentifierCodePoint(std::uint32_t c)noexcept{return c<32||c==127;}bool Lexer::isOperatorCharacter(char c)noexcept{return isOp(c);}bool Lexer::isOperatorStartCharacter(char c)noexcept{return isOp(c);}bool Lexer::isOperatorContinuationCharacter(char c)noexcept{return isOp(c);}
bool Lexer::looksLikeEditorPlaceholder(std::string_view s)noexcept{return s.size()>2&&s.front()=='<'&&s.back()=='>';}bool Lexer::looksLikeDirective(std::string_view s)noexcept{return s.size()>1&&s.front()=='#'&&isIdStart(s[1]);}bool Lexer::looksLikeConflictMarker(std::string_view s)noexcept{return s.rfind("<<<<<<<",0)==0||s.rfind("=======",0)==0||s.rfind(">>>>>>>",0)==0;}
OperatorBinding Lexer::classifyOperatorBinding(std::string_view s,std::size_t a,std::size_t b)noexcept{bool left=a>0&&!std::isspace((unsigned char)s[a-1]);bool right=b<s.size()&&!std::isspace((unsigned char)s[b]);if(!left&&!right)return OperatorBinding::BinarySpaced;if(left&&right)return OperatorBinding::BinaryUnspaced;if(left)return OperatorBinding::Postfix;return OperatorBinding::Prefix;}
bool Lexer::isIdentifier(std::string_view s){if(s.empty()||!isIdStart(s.front()))return false;for(char c:s)if(!isIdPart(c))return false;return true;}bool Lexer::isOperator(std::string_view s){if(s.empty())return false;for(char c:s)if(!isOp(c))return false;return true;}bool Lexer::isValidEscapedIdentifier(std::string_view s){return s.size()>=2&&s.front()=='`'&&s.back()=='`';}
std::uint32_t Lexer::validateUTF8Character(std::string_view b,std::size_t&p){if(p>=b.size())return 0xFFFFFFFFu;unsigned char c=b[p++];if(c<128)return c;int n=(c&224)==192?1:(c&240)==224?2:(c&248)==240?3:0;if(!n)return 0xFFFFFFFFu;std::uint32_t v=c&((1u<<(7-n))-1);for(int i=0;i<n;++i){if(p>=b.size()||(b[p]&192)!=128)return 0xFFFFFFFFu;v=(v<<6)|(b[p++]&63);}return v;}
bool Lexer::encodeUTF8(std::uint32_t c,std::string&o){if(c>0x10FFFF||(c>=0xD800&&c<=0xDFFF))return false;if(c<128)o.push_back((char)c);else if(c<2048){o.push_back((char)(192|(c>>6)));o.push_back((char)(128|(c&63)));}else if(c<65536){o.push_back((char)(224|(c>>12)));o.push_back((char)(128|((c>>6)&63)));o.push_back((char)(128|(c&63)));}else{o.push_back((char)(240|(c>>18)));o.push_back((char)(128|((c>>12)&63)));o.push_back((char)(128|((c>>6)&63)));o.push_back((char)(128|(c&63)));}return true;}
bool Lexer::scanInterpolatedExpression(std::size_t,std::size_t&){return false;}bool Lexer::scanStringDelimiter(std::size_t&,bool&){return false;}bool Lexer::scanUnicodeEscape(std::size_t&,std::uint32_t&){return false;}bool Lexer::scanEscapeSequence(std::size_t&,std::string&,bool&){return false;}
void Lexer::invalidateLookahead(){lookaheadBuffer_.clear();}
const char* tokenKindName(K k)noexcept{switch(k){case K::EndOfFile:return "eof";case K::Identifier:return "identifier";case K::IntegerLiteral:return "integer";case K::FloatLiteral:return "float";case K::StringLiteral:return "string";case K::CharacterLiteral:return "character";case K::KwFunc:return "func";case K::KwVar:return "var";case K::KwLet:return "let";case K::KwIf:return "if";case K::KwElse:return "else";case K::KwReturn:return "return";case K::Equal:return "=";case K::EqualEqual:return "==";case K::NotEqual:return "!=";case K::PlusEqual:return "+=";case K::MinusEqual:return "-=";case K::StarEqual:return "*=";case K::GreaterEqual:return ">=";case K::LessEqual:return "<=";case K::TildeEqual:return "~=";case K::LeftBrace:return "{";case K::RightBrace:return "}";case K::LeftParen:return "(";case K::RightParen:return ")";case K::Dot:return ".";case K::Comma:return ",";case K::Colon:return ":";case K::Semicolon:return ";";case K::Unknown:return "unknown";default:return "token";}}
}
