#include "hyper/lib/Parse/Token.h"
namespace hyper::parse {
std::string_view tokenKindName(TokenKind k)noexcept{switch(k){
case TokenKind::Eof: return "eof";
case TokenKind::Unknown: return "unknown";
case TokenKind::Identifier: return "identifier";
case TokenKind::Keyword: return "keyword";
case TokenKind::SpecialKeyword: return "special_keyword";
case TokenKind::IntegerLiteral: return "integer_literal";
case TokenKind::FloatingLiteral: return "floating_literal";
case TokenKind::StringLiteral: return "string_literal";
case TokenKind::CharacterLiteral: return "character_literal";
case TokenKind::TrueLiteral: return "true_literal";
case TokenKind::FalseLiteral: return "false_literal";
case TokenKind::NilLiteral: return "nil_literal";
case TokenKind::LParen: return "l_paren";
case TokenKind::RParen: return "r_paren";
case TokenKind::LBrace: return "l_brace";
case TokenKind::RBrace: return "r_brace";
case TokenKind::LBracket: return "l_bracket";
case TokenKind::RBracket: return "r_bracket";
case TokenKind::Comma: return "comma";
case TokenKind::Dot: return "dot";
case TokenKind::Colon: return "colon";
case TokenKind::Semicolon: return "semicolon";
case TokenKind::Question: return "question";
case TokenKind::At: return "at";
case TokenKind::Plus: return "plus";
case TokenKind::Minus: return "minus";
case TokenKind::Star: return "star";
case TokenKind::Slash: return "slash";
case TokenKind::Percent: return "percent";
case TokenKind::Ampersand: return "ampersand";
case TokenKind::Pipe: return "pipe";
case TokenKind::Caret: return "caret";
case TokenKind::Tilde: return "tilde";
case TokenKind::Bang: return "bang";
case TokenKind::Equal: return "equal";
case TokenKind::Less: return "less";
case TokenKind::Greater: return "greater";
case TokenKind::PlusEqual: return "plus_equal";
case TokenKind::MinusEqual: return "minus_equal";
case TokenKind::StarEqual: return "star_equal";
case TokenKind::SlashEqual: return "slash_equal";
case TokenKind::PercentEqual: return "percent_equal";
case TokenKind::AmpEqual: return "amp_equal";
case TokenKind::PipeEqual: return "pipe_equal";
case TokenKind::CaretEqual: return "caret_equal";
case TokenKind::EqualEqual: return "equal_equal";
case TokenKind::BangEqual: return "bang_equal";
case TokenKind::LessEqual: return "less_equal";
case TokenKind::GreaterEqual: return "greater_equal";
case TokenKind::AmpAmp: return "amp_amp";
case TokenKind::PipePipe: return "pipe_pipe";
case TokenKind::Arrow: return "arrow";
case TokenKind::FatArrow: return "fat_arrow";
case TokenKind::Increment: return "increment";
case TokenKind::Decrement: return "decrement";
case TokenKind::ShiftLeft: return "shift_left";
case TokenKind::ShiftRight: return "shift_right";
case TokenKind::ShiftLeftEqual: return "shift_left_equal";
case TokenKind::ShiftRightEqual: return "shift_right_equal";
case TokenKind::Range: return "range";
case TokenKind::RangeInclusive: return "range_inclusive";
case TokenKind::NullCoalescing: return "null_coalescing";
case TokenKind::Scope: return "scope";
case TokenKind::Ellipsis: return "ellipsis";
case TokenKind::DoubleColon: return "double_colon";
case TokenKind::QuestionDot: return "question_dot";
case TokenKind::BangDot: return "bang_dot";
case TokenKind::AtApi: return "at_api";
case TokenKind::AtApiId: return "at_api_id";
case TokenKind::AtFile: return "at_file";
case TokenKind::AtFilename: return "at_filename";
case TokenKind::AtFileId: return "at_file_id";
case TokenKind::AtAudio: return "at_audio";
case TokenKind::AtPlayAudio: return "at_play_audio";
case TokenKind::AtImage: return "at_image";
case TokenKind::AtImageId: return "at_image_id";
}return "unknown";}
bool isKeyword(TokenKind k)noexcept{return k==TokenKind::Keyword||k==TokenKind::TrueLiteral||k==TokenKind::FalseLiteral||k==TokenKind::NilLiteral;}
bool isSpecialKeyword(TokenKind k)noexcept{return k>=TokenKind::AtApi&&k<=TokenKind::AtImageId;}
bool isLiteral(TokenKind k)noexcept{return k>=TokenKind::IntegerLiteral&&k<=TokenKind::NilLiteral;}
bool isPunctuation(TokenKind k)noexcept{switch(k){case TokenKind::LParen:case TokenKind::RParen:case TokenKind::LBrace:case TokenKind::RBrace:case TokenKind::LBracket:case TokenKind::RBracket:case TokenKind::Comma:case TokenKind::Dot:case TokenKind::Colon:case TokenKind::Semicolon:case TokenKind::Question:return true;default:return false;}}
bool isOperator(TokenKind k)noexcept{return k>=TokenKind::Plus&&k<=TokenKind::BangDot;}
}
