// MARK: - Transpiler Configuration

public struct TranspilerConfig {
    public var indentSize: Int = 4
    public init(indentSize: Int = 4) {
        self.indentSize = indentSize
    }
}

// MARK: - Code Generator

public final class CodeGenerator: ExprVisitor, StmtVisitor, DeclVisitor, TypeVisitor {
    public typealias ExprResult = String
    public typealias StmtResult = String
    public typealias DeclResult = String
    public typealias TypeResult = String
    
    private let config: TranspilerConfig
    private var indentLevel: Int = 0
    
    public init(config: TranspilerConfig = TranspilerConfig()) {
        self.config = config
    }
    
    public func generate(from ast: [Decl]) throws -> String {
        var output = "// Auto-generated by HyperLang Transpiler\nimport Foundation\n\n"
        
        for decl in ast {
            output += try decl.accept(visitor: self) + "\n\n"
        }
        
        return output.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }
    
    // MARK: - Formatting Helpers
    
    private func indent() { indentLevel += 1 }
    private func dedent() { indentLevel -= 1 }
    
    private func getIndent() -> String {
        return String(repeating: " ", count: indentLevel * config.indentSize)
    }
    
    private func modifiersString(_ modifiers: [Token]) -> String {
        if modifiers.isEmpty { return "" }
        // HyperLang `public`, `private`, `mut`, etc. map cleanly to Swift
        let mods = modifiers.map { $0.lexeme }.joined(separator: " ")
        return "\(mods) "
    }
    
    // MARK: - Declaration Visitor
    
    public func visit(moduleDecl: ModuleDecl) throws -> String {
        return "// module \(moduleDecl.name.lexeme)"
    }
    
    public func visit(includeDecl: IncludeDecl) throws -> String {
        return "import \(includeDecl.modulePath.lexeme)"
    }
    
    public func visit(varDecl: VarDecl) throws -> String {
        // Map `val` to `let`, `var` to `var`
        let keyword = varDecl.keyword.lexeme == "val" ? "let" : "var"
        var out = "\(getIndent())\(keyword) \(varDecl.name.lexeme)"
        
        if let typeAnn = varDecl.typeAnnotation {
            out += ": \(try typeAnn.accept(visitor: self))"
        }
        
        if let initExpr = varDecl.initializer {
            out += " = \(try initExpr.accept(visitor: self))"
        }
        
        return out
    }
    
    public func visit(defDecl: DefDecl) throws -> String {
        var out = getIndent() + modifiersString(defDecl.modifiers)
        out += "func \(defDecl.name.lexeme)("
        
        let params = try defDecl.parameters.map { param -> String in
            let inoutMod = param.inoutModifier != nil ? "inout " : ""
            let typeStr = try param.type.accept(visitor: self)
            return "\(inoutMod)\(param.name.lexeme): \(typeStr)"
        }
        out += params.joined(separator: ", ") + ")"
        
        if defDecl.isAsync { out += " async" }
        if defDecl.isThrows { out += " throws" }
        
        if let retType = defDecl.returnType {
            out += " -> \(try retType.accept(visitor: self))"
        }
        
        if let body = defDecl.body {
            out += " \(try body.accept(visitor: self))"
        } else {
            out += " {}"
        }
        
        return out
    }
    
    public func visit(classDecl: ClassDecl) throws -> String {
        var out = getIndent() + modifiersString(classDecl.modifiers) + "class \(classDecl.name.lexeme)"
        if let superclass = classDecl.superclass {
            out += ": \(try superclass.accept(visitor: self))"
        }
        out += " {\n"
        indent()
        for member in classDecl.members {
            out += try member.accept(visitor: self) + "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(structDecl: StructDecl) throws -> String {
        var out = getIndent() + modifiersString(structDecl.modifiers) + "struct \(structDecl.name.lexeme) {\n"
        indent()
        for member in structDecl.members {
            out += try member.accept(visitor: self) + "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(interfaceDecl: InterfaceDecl) throws -> String {
        // HyperLang `interface` becomes Swift `protocol`
        var out = getIndent() + modifiersString(interfaceDecl.modifiers) + "protocol \(interfaceDecl.name.lexeme) {\n"
        indent()
        for member in interfaceDecl.members {
            out += try member.accept(visitor: self) + "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(actorDecl: ActorDecl) throws -> String {
        var out = getIndent() + modifiersString(actorDecl.modifiers) + "actor \(actorDecl.name.lexeme) {\n"
        indent()
        for member in actorDecl.members {
            out += try member.accept(visitor: self) + "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(enumDecl: EnumDecl) throws -> String {
        var out = getIndent() + modifiersString(enumDecl.modifiers) + "enum \(enumDecl.name.lexeme) {\n"
        indent()
        for c in enumDecl.cases {
            out += getIndent() + "case \(c.name.lexeme)"
            if let assoc = c.associatedTypes {
                let types = try assoc.map { try $0.accept(visitor: self) }.joined(separator: ", ")
                out += "(\(types))"
            }
            out += "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(initDecl: InitDecl) throws -> String {
        var out = getIndent() + modifiersString(initDecl.modifiers) + "init("
        let params = try initDecl.parameters.map { param -> String in
            let typeStr = try param.type.accept(visitor: self)
            return "\(param.name.lexeme): \(typeStr)"
        }
        out += params.joined(separator: ", ") + ")"
        if initDecl.isThrows { out += " throws" }
        out += " \(try initDecl.body.accept(visitor: self))"
        return out
    }
    
    public func visit(deinitDecl: DeinitDecl) throws -> String {
        return getIndent() + "deinit \(try deinitDecl.body.accept(visitor: self))"
    }
    
    // MARK: - Statement Visitor
    
    public func visit(expressionStmt: ExpressionStmt) throws -> String {
        return getIndent() + (try expressionStmt.expression.accept(visitor: self))
    }
    
    public func visit(blockStmt: BlockStmt) throws -> String {
        var out = "{\n"
        indent()
        for stmt in blockStmt.statements {
            let stmtStr = try stmt is Decl ? (stmt as! Decl).accept(visitor: self) : stmt.accept(visitor: self)
            out += stmtStr + "\n"
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(ifStmt: IfStmt) throws -> String {
        var out = getIndent() + "if \(try ifStmt.condition.accept(visitor: self)) \(try ifStmt.thenBranch.accept(visitor: self))"
        if let el = ifStmt.elseBranch {
            if el is IfStmt {
                // To prevent double indenting `else if`
                let elStr = try el.accept(visitor: self).trimmingCharacters(in: .whitespaces)
                out += " else \(elStr)"
            } else {
                out += " else \(try el.accept(visitor: self))"
            }
        }
        return out
    }
    
    public func visit(whileStmt: WhileStmt) throws -> String {
        return getIndent() + "while \(try whileStmt.condition.accept(visitor: self)) \(try whileStmt.body.accept(visitor: self))"
    }
    
    public func visit(loopStmt: LoopStmt) throws -> String {
        return getIndent() + "while true \(try loopStmt.body.accept(visitor: self))"
    }
    
    public func visit(forInStmt: ForInStmt) throws -> String {
        return getIndent() + "for \(forInStmt.iterator.lexeme) in \(try forInStmt.iterable.accept(visitor: self)) \(try forInStmt.body.accept(visitor: self))"
    }
    
    public func visit(whenStmt: WhenStmt) throws -> String {
        // HyperLang `when` becomes Swift `switch`
        var out = getIndent() + "switch "
        if let sub = whenStmt.subject {
            out += try sub.accept(visitor: self) + " {\n"
        } else {
            out += "true {\n"
        }
        
        indent()
        for c in whenStmt.cases {
            out += getIndent() + "case \(try c.pattern.accept(visitor: self)):\n"
            indent()
            for stmt in c.body.statements {
                out += try stmt.accept(visitor: self) + "\n"
            }
            dedent()
        }
        if let def = whenStmt.defaultCase {
            out += getIndent() + "default:\n"
            indent()
            for stmt in def.statements {
                out += try stmt.accept(visitor: self) + "\n"
            }
            dedent()
        }
        dedent()
        out += getIndent() + "}"
        return out
    }
    
    public func visit(returnStmt: ReturnStmt) throws -> String {
        if let val = returnStmt.value {
            return getIndent() + "return \(try val.accept(visitor: self))"
        }
        return getIndent() + "return"
    }
    
    public func visit(breakStmt: BreakStmt) throws -> String {
        return getIndent() + "break"
    }
    
    public func visit(continueStmt: ContinueStmt) throws -> String {
        return getIndent() + "continue"
    }
    
    public func visit(passStmt: PassStmt) throws -> String {
        return getIndent() + "/* pass */"
    }
    
    public func visit(raiseStmt: RaiseStmt) throws -> String {
        return getIndent() + "throw \(try raiseStmt.value.accept(visitor: self))"
    }
    
    public func visit(spawnStmt: SpawnStmt) throws -> String {
        return getIndent() + "Task { \(try spawnStmt.call.accept(visitor: self)) }"
    }
    
    public func visit(deferStmt: DeferStmt) throws -> String {
        return getIndent() + "defer \(try deferStmt.body.accept(visitor: self))"
    }
    
    public func visit(guardStmt: GuardStmt) throws -> String {
        return getIndent() + "guard \(try guardStmt.condition.accept(visitor: self)) else \(try guardStmt.body.accept(visitor: self))"
    }
    
    // MARK: - Expression Visitor
    
    public func visit(identifierExpr: IdentifierExpr) throws -> String {
        let lexeme = identifierExpr.name.lexeme
        // Map Python-flavored `self` / `None` / `Self` to Swift equivalents
        if lexeme == "None" { return "nil" }
        return lexeme
    }
    
    public func visit(literalExpr: LiteralExpr) throws -> String {
        if literalExpr.value.lexeme == "None" { return "nil" }
        return literalExpr.value.lexeme
    }
    
    public func visit(binaryExpr: BinaryExpr) throws -> String {
        let left = try binaryExpr.left.accept(visitor: self)
        let right = try binaryExpr.right.accept(visitor: self)
        return "\(left) \(binaryExpr.operatorToken.lexeme) \(right)"
    }
    
    public func visit(unaryExpr: UnaryExpr) throws -> String {
        let right = try unaryExpr.right.accept(visitor: self)
        return "\(unaryExpr.operatorToken.lexeme)\(right)"
    }
    
    public func visit(logicalExpr: LogicalExpr) throws -> String {
        let left = try logicalExpr.left.accept(visitor: self)
        let right = try logicalExpr.right.accept(visitor: self)
        return "\(left) \(logicalExpr.operatorToken.lexeme) \(right)"
    }
    
    public func visit(callExpr: CallExpr) throws -> String {
        let callee = try callExpr.callee.accept(visitor: self)
        let args = try callExpr.arguments.map { try $0.accept(visitor: self) }.joined(separator: ", ")
        return "\(callee)(\(args))"
    }
    
    public func visit(memberAccessExpr: MemberAccessExpr) throws -> String {
        let obj = try memberAccessExpr.object.accept(visitor: self)
        return "\(obj).\(memberAccessExpr.name.lexeme)"
    }
    
    public func visit(assignmentExpr: AssignmentExpr) throws -> String {
        let val = try assignmentExpr.value.accept(visitor: self)
        return "\(assignmentExpr.name.lexeme) = \(val)"
    }
    
    public func visit(tryExpr: TryExpr) throws -> String {
        return "try \(try tryExpr.expression.accept(visitor: self))"
    }
    
    public func visit(awaitExpr: AwaitExpr) throws -> String {
        return "await \(try awaitExpr.expression.accept(visitor: self))"
    }
    
    public func visit(castExpr: CastExpr) throws -> String {
        let expr = try castExpr.expression.accept(visitor: self)
        let target = try castExpr.targetType.accept(visitor: self)
        return "\(expr) as! \(target)"
    }
    
    // MARK: - Type Visitor
    
    public func visit(simpleTypeExpr: SimpleTypeExpr) throws -> String {
        return simpleTypeExpr.name.lexeme
    }
    
    public func visit(optionalTypeExpr: OptionalTypeExpr) throws -> String {
        return "\(try optionalTypeExpr.baseType.accept(visitor: self))?"
    }
}
