# Shared build rules for HyperLang compiler stages.
function(hyperlang_configure_stage target)
    target_compile_features(${target} PUBLIC cxx_std_20)
    target_include_directories(${target} PUBLIC ${PROJECT_SOURCE_DIR}/include)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /O2)
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -O2)
    endif()
endfunction()
